version: 2
updates:
  - package-ecosystem: pip
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
    groups:
      python-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/London
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/London
    open-pull-requests-limit: 2
