"""Bounded G-code scanning and slicer-signature classification for one selected member."""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from zipfile import ZipFile, ZipInfo

from klove.domain.artifact_archive import _PARSER_ERRORS, _Denied
from klove.domain.artifact_contract_models import (
    ArtifactBoundary,
    ArtifactFailureCode,
    ArtifactLimits,
)

_CHUNK_BYTES = 64 * 1024
_SUPPORTED_GENERATORS = (
    b"generated by orcaslicer",
    b"generated by prusaslicer",
    b"generated by superslicer",
)
_BAMBU_GENERATORS = (b"generated by bambustudio", b"generated by bambu studio")
_COMMAND = re.compile(
    rb"^(?:/[ \t]*)?(?:N[0-9]+[ \t]*)?([GMT][0-9]+(?:\.[0-9]+)?)",
    re.IGNORECASE,
)
_MOTION_AXIS = re.compile(
    rb"(?:^|[ \t])[XYZE][+-]?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?=$|[ \t]|[XYZEFS])",
    re.IGNORECASE,
)


@dataclass(frozen=True, slots=True)
class _SelectedGcode:
    sha256: str
    size_bytes: int


def _read_selected_gcode(
    bundle: ZipFile, selected: ZipInfo, limits: ArtifactLimits
) -> _SelectedGcode:
    """Stream the exact selected member through bounded syntax, digest, and CRC checks."""
    digest = hashlib.sha256()
    size_bytes = 0
    scanner = _GcodeScanner(limits)
    try:
        with bundle.open(selected, mode="r") as source:
            while chunk := source.read(_CHUNK_BYTES):
                if not isinstance(chunk, bytes) or len(chunk) > _CHUNK_BYTES:
                    raise _Denied(
                        ArtifactBoundary.SELECTED_PLATE,
                        ArtifactFailureCode.INTEGRITY_FAILED,
                    )
                size_bytes += len(chunk)
                if size_bytes > limits.max_gcode_bytes or size_bytes > selected.file_size:
                    raise _Denied(
                        ArtifactBoundary.SELECTED_PLATE,
                        ArtifactFailureCode.LIMIT_EXCEEDED,
                    )
                digest.update(chunk)
                scanner.feed(chunk)
    except _Denied:
        raise
    except _PARSER_ERRORS as error:
        raise _Denied(
            ArtifactBoundary.SELECTED_PLATE,
            ArtifactFailureCode.INTEGRITY_FAILED,
        ) from error
    if size_bytes != selected.file_size:
        raise _Denied(
            ArtifactBoundary.SELECTED_PLATE,
            ArtifactFailureCode.INTEGRITY_FAILED,
        )
    scanner.finish()
    return _SelectedGcode(sha256="sha256:" + digest.hexdigest(), size_bytes=size_bytes)


class _GcodeScanner:
    """Incrementally classify bounded ASCII Klipper G-code without retaining its body."""

    def __init__(self, limits: ArtifactLimits) -> None:
        self._limits = limits
        self._line = bytearray()
        self._line_start = 0
        self._consumed = 0
        self._supported_generator = False
        self._executable_seen = False
        self._motion_seen = False

    def feed(self, content: bytes) -> None:
        """Consume one decompressed byte chunk."""
        for byte in content:
            if self._line and self._line[-1] == 13 and byte != 10:
                raise _Denied(ArtifactBoundary.SELECTED_PLATE, ArtifactFailureCode.INVALID_GCODE)
            if byte == 10:
                line = bytes(self._line[:-1] if self._line.endswith(b"\r") else self._line)
                self._inspect_line(line)
                self._line.clear()
                self._consumed += 1
                self._line_start = self._consumed
                continue
            if byte not in {9, 13} and not 32 <= byte <= 126:
                raise _Denied(ArtifactBoundary.SELECTED_PLATE, ArtifactFailureCode.INVALID_GCODE)
            self._line.append(byte)
            self._consumed += 1
            content_bytes = len(self._line) - int(self._line.endswith(b"\r"))
            if content_bytes > self._limits.max_gcode_line_bytes:
                raise _Denied(ArtifactBoundary.SELECTED_PLATE, ArtifactFailureCode.LIMIT_EXCEEDED)

    def finish(self) -> None:
        """Validate the final line and the complete recognized structure."""
        if self._line.endswith(b"\r"):
            raise _Denied(ArtifactBoundary.SELECTED_PLATE, ArtifactFailureCode.INVALID_GCODE)
        if self._line:
            self._inspect_line(bytes(self._line))
        if not self._supported_generator or not self._executable_seen or not self._motion_seen:
            raise _Denied(ArtifactBoundary.SELECTED_PLATE, ArtifactFailureCode.INVALID_GCODE)

    def _inspect_line(self, line: bytes) -> None:
        """Inspect one already bounded and canonicalized line."""
        stripped = line.strip(b" \t")
        if stripped.startswith(b";"):
            lowered = stripped.lower()
            if any(marker in lowered for marker in _BAMBU_GENERATORS):
                raise _Denied(
                    ArtifactBoundary.SELECTED_PLATE,
                    ArtifactFailureCode.INCOMPATIBLE_GCODE,
                )
            if not self._executable_seen and any(
                marker in lowered for marker in _SUPPORTED_GENERATORS
            ):
                self._supported_generator = True

        code = line.partition(b";")[0].strip(b" \t")
        if code:
            if not self._executable_seen and self._line_start > self._limits.max_gcode_header_bytes:
                raise _Denied(ArtifactBoundary.SELECTED_PLATE, ArtifactFailureCode.LIMIT_EXCEEDED)
            self._executable_seen = True
            match = _COMMAND.match(code)
            if match:
                command = match.group(1).upper()
                if _is_bambu_command(command):
                    raise _Denied(
                        ArtifactBoundary.SELECTED_PLATE,
                        ArtifactFailureCode.INCOMPATIBLE_GCODE,
                    )
                if command in {b"G0", b"G00", b"G1", b"G01"} and _MOTION_AXIS.search(
                    code[match.end() :]
                ):
                    self._motion_seen = True


def _is_bambu_command(command: bytes) -> bool:
    """Return whether one exact executable token is known to require Bambu firmware."""
    if command in {b"M73.2", b"M1002", b"T1000"}:
        return True
    if not command.startswith(b"M"):
        return False
    number = int(command[1:].partition(b".")[0])
    return 620 <= number <= 623 or number == 960 or 970 <= number <= 989
