"""Native, test-only proof of the internal ADR-0007 dispatch coordinator."""

from __future__ import annotations

import asyncio
import hashlib
import json
import urllib.request
from collections.abc import AsyncIterator
from dataclasses import dataclass
from io import BytesIO
from pathlib import Path
from typing import Any
from zipfile import ZIP_STORED, ZipFile

import aiohttp
from sdcard_reset import reset_virtual_sd_after_completed_print

from klove.adapters.moonraker.start import MoonrakerStartTransport
from klove.adapters.moonraker.upload import MoonrakerUploadTransport
from klove.config import PrinterConfig
from klove.domain.artifacts import (
    ArtifactCompatibility,
    ArtifactLimits,
    BuildVolume,
    GcodeFlavor,
    PlateSelection,
    SafetyProfile,
    target_for_safety_profile,
)
from klove.domain.discovery import discover_capabilities
from klove.domain.dispatch import (
    DispatchFailureCode,
    DispatchGrant,
    DispatchJournalRecord,
    DispatchOperationResult,
    DispatchRequest,
    DispatchState,
)
from klove.domain.models import JobHistoryStatus, JobIdentitySnapshot, PrinterPhase
from klove.domain.onboarding import (
    MoonrakerEndpoint,
    PrinterIdentityEvidence,
    PrinterLifecycle,
    RegisteredPrinter,
)
from klove.orchestration.admission import PrinterAdmissionGates
from klove.orchestration.dispatch import DispatchCoordinator, DispatchReceiveLimiter
from klove.orchestration.start import StartService
from klove.orchestration.upload import UploadService
from klove.persistence.dispatch_journal import DispatchJournal
from klove.persistence.dispatch_spool import DispatchSpool
from klove.persistence.private_files import PrivateFileError, require_private_directory
from klove.persistence.start_journal import StartJournal

PRINTER_UUID = "11111111-1111-4111-8111-111111111111"
OTHER_PRINTER_UUID = "22222222-2222-4222-8222-222222222222"
PROFILE = SafetyProfile(
    printer_uuid=PRINTER_UUID,
    generation=1,
    slicer_profile_id="fixture-klipper-0.4",
    compatibility=ArtifactCompatibility(
        gcode_flavor=GcodeFlavor.KLIPPER,
        nozzle_diameter_micrometres=400,
        build_volume=BuildVolume(
            x_micrometres=350_000,
            y_micrometres=350_000,
            z_micrometres=350_000,
        ),
        build_plate_id="fixture-plate",
    ),
)
TARGET = target_for_safety_profile(PROFILE)
GRANT = DispatchGrant(principal_id="native-dispatch-proof", printer_uuid=PRINTER_UUID)
STATE_DIRECTORY = Path("/var/lib/klove/native-dispatch-proof")
API_KEY_PATH = Path("/run/klove-secrets/moonraker-api-key")
PROXY_CONTROL = "http://moonraker-proxy:9126"
SELECTED_PATH = "Metadata/plate_1.gcode"
NORMAL_OPERATION_ID = "10000000-0000-4000-8000-000000000001"
NORMAL_IDEMPOTENCY_KEY = "10000000-0000-4000-8000-000000000002"
CANCEL_OPERATION_ID = "10000000-0000-4000-8000-000000000003"
CANCEL_IDEMPOTENCY_KEY = "10000000-0000-4000-8000-000000000004"
AMBIGUOUS_OPERATION_ID = "10000000-0000-4000-8000-000000000005"
AMBIGUOUS_IDEMPOTENCY_KEY = "10000000-0000-4000-8000-000000000006"
SOURCE_MISMATCH_OPERATION_ID = "10000000-0000-4000-8000-000000000011"
SOURCE_MISMATCH_IDEMPOTENCY_KEY = "10000000-0000-4000-8000-000000000012"

# The coordinate-bearing move remains zero-distance in the fixture's
# `kinematics: none` environment; the remaining commands are finite waits.
GCODE = (
    b"; generated by OrcaSlicer 2.3.0 on 2026-01-01 at 00:00:00\n"
    b"; nozzle_diameter = 0.4\nG1 X0 Y0\n"
) + (b"G4 P1000\n" * 12)


class _Registry:
    def __init__(self, record: RegisteredPrinter) -> None:
        self._record = record

    def get(self, printer_uuid: str) -> RegisteredPrinter | None:
        return self._record if printer_uuid == self._record.printer_uuid else None


@dataclass(slots=True)
class _Runtime:
    coordinator: DispatchCoordinator
    journal: DispatchJournal
    session: aiohttp.ClientSession
    transport: MoonrakerStartTransport

    async def close(self) -> None:
        await self.session.close()


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def _archive() -> bytes:
    target = BytesIO()
    with ZipFile(target, mode="w", compression=ZIP_STORED) as bundle:
        bundle.writestr("[Content_Types].xml", b"<Types/>")
        bundle.writestr("_rels/.rels", b"<Relationships/>")
        bundle.writestr("3D/3dmodel.model", b"<model/>")
        bundle.writestr(SELECTED_PATH, GCODE)
    return target.getvalue()


def _request(operation_id: str, idempotency_key: str, archive: bytes) -> DispatchRequest:
    return DispatchRequest(
        operation_id=operation_id,
        idempotency_key=idempotency_key,
        printer_uuid=PRINTER_UUID,
        slicer_profile_id=PROFILE.slicer_profile_id,
        safety_profile_generation=PROFILE.generation,
        safety_profile_fingerprint=TARGET.safety_profile_fingerprint,
        selected_plate=PlateSelection(plate_id="1", archive_path=SELECTED_PATH),
        archive_sha256=f"sha256:{hashlib.sha256(archive).hexdigest()}",
        archive_size_bytes=len(archive),
    )


async def _stream(archive: bytes) -> AsyncIterator[bytes]:
    yield archive


async def _stalled_stream(entered: asyncio.Event) -> AsyncIterator[bytes]:
    entered.set()
    await asyncio.Event().wait()
    yield b"unreachable"


def _read_api_key() -> str:
    value = API_KEY_PATH.read_text(encoding="utf-8").strip()
    if len(value) < 32:
        raise RuntimeError("fixture Moonraker credential is unavailable")
    return value


def _record() -> RegisteredPrinter:
    return RegisteredPrinter(
        printer_uuid=PRINTER_UUID,
        display_name="Native dispatch fixture",
        endpoint=MoonrakerEndpoint(
            url="http://moonraker-proxy:7125",
            allow_insecure_http=True,
            verify_tls=False,
        ),
        lifecycle=PrinterLifecycle.ACTIVE,
        moonraker_credential_ref="credential-10000000-0000-4000-8000-000000000007",
        compatibility_credential_ref="credential-10000000-0000-4000-8000-000000000008",
        identity=PrinterIdentityEvidence(
            server_hostname="native-fixture-moonraker",
            klipper_hostname="native-fixture-klipper",
            moonraker_version="pinned-native-fixture",
            klipper_version="pinned-native-fixture",
            capabilities=discover_capabilities({"pause_resume", "print_stats", "virtual_sdcard"}),
            observed_at_unix_ms=1,
        ),
        safety_profiles=(PROFILE,),
        control_enabled=False,
        dispatch_enabled=True,
        revision=1,
        created_at_unix_ms=1,
        updated_at_unix_ms=1,
    )


def _prepare_state_directory() -> None:
    """Create the test-only durable journal directory before async transport work."""
    spool_directory = STATE_DIRECTORY / "spool"
    try:
        STATE_DIRECTORY.mkdir(parents=True, exist_ok=True, mode=0o700)
        STATE_DIRECTORY.chmod(0o700)
        spool_directory.mkdir(exist_ok=True, mode=0o700)
        spool_directory.chmod(0o700)
        require_private_directory(STATE_DIRECTORY)
        require_private_directory(spool_directory)
    except (OSError, PrivateFileError, ValueError) as error:
        raise RuntimeError("dispatch fixture state directory is not owner-only") from error


async def _runtime() -> _Runtime:
    _prepare_state_directory()
    api_key = _read_api_key()
    config = PrinterConfig(
        id="native-dispatch-fixture",
        uuid=PRINTER_UUID,
        endpoint="http://moonraker-proxy:7125",
        api_key_file=API_KEY_PATH,
        allow_insecure_http=True,
        verify_tls=False,
        dispatch_enabled=True,
        safety_profiles=(PROFILE,),
    )
    limits = ArtifactLimits(metadata_wait_seconds=10.0, metadata_poll_interval_seconds=0.1)
    admissions = PrinterAdmissionGates()
    session = aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=10))
    uploader = UploadService(
        config,
        MoonrakerUploadTransport(config, api_key, session, request_timeout_seconds=10),
        limits=limits,
        admissions=admissions,
    )
    transport = MoonrakerStartTransport(config, api_key, session, request_timeout_seconds=10)
    starter = StartService(
        config,
        transport,
        StartJournal(STATE_DIRECTORY / "start.sqlite3"),
        enabled=True,
        confirmation_timeout_seconds=1.0,
        poll_interval_seconds=0.1,
        admissions=admissions,
    )
    try:
        await starter.initialize()
        journal = DispatchJournal(STATE_DIRECTORY / "dispatch.sqlite3")
        coordinator = DispatchCoordinator(
            PRINTER_UUID,
            _Registry(_record()),
            uploader,
            starter,
            journal,
            DispatchSpool(STATE_DIRECTORY / "spool", limits=limits),
            limits=limits,
            operation_capacity=16,
            admissions=admissions,
            receive_limiter=DispatchReceiveLimiter(2),
            receive_timeout_seconds=30,
        )
        await coordinator.initialize()
    except BaseException:
        await session.close()
        raise
    return _Runtime(
        coordinator=coordinator,
        journal=journal,
        session=session,
        transport=transport,
    )


async def _wait_state(
    coordinator: DispatchCoordinator,
    request: DispatchRequest,
    expected: DispatchState,
    *,
    timeout: float = 30,
) -> DispatchOperationResult:
    deadline = asyncio.get_running_loop().time() + timeout
    latest: DispatchOperationResult | None = None
    while asyncio.get_running_loop().time() < deadline:
        latest = await coordinator.result(GRANT, request.operation_id, request.idempotency_key)
        if latest is not None and latest.state is expected:
            return latest
        await asyncio.sleep(0.1)
    raise RuntimeError(f"dispatch did not reach {expected.value}: {latest!r}")


async def _wait_persisted_state(
    journal: DispatchJournal,
    request: DispatchRequest,
    expected: DispatchState,
    *,
    timeout: float = 30,
) -> DispatchJournalRecord:
    """Observe one durable state without triggering read-only reconciliation."""
    deadline = asyncio.get_running_loop().time() + timeout
    latest: DispatchJournalRecord | None = None
    while asyncio.get_running_loop().time() < deadline:
        latest = journal.lookup(request.operation_id, request.idempotency_key)
        if latest is not None and latest.state is expected:
            return latest
        await asyncio.sleep(0.1)
    raise RuntimeError(f"dispatch did not persist {expected.value}: {latest!r}")


async def _wait_for_idle(
    transport: MoonrakerStartTransport,
    *,
    expected_latest_job: JobIdentitySnapshot | None,
    timeout: float = 15,
) -> None:
    """Require the transport's bracketed history/object/history idle observation."""
    deadline = asyncio.get_running_loop().time() + timeout
    latest_error = "no observation"
    while asyncio.get_running_loop().time() < deadline:
        try:
            observation = await transport.query()
        except Exception as error:
            latest_error = type(error).__name__
        else:
            if (
                observation.phase is PrinterPhase.IDLE
                and observation.filename == ""
                and observation.file_position == 0
                and observation.latest_job == expected_latest_job
            ):
                return
            latest_error = repr(observation)
        await asyncio.sleep(0.1)
    raise RuntimeError(f"fixture did not return to a coherent idle state: {latest_error}")


async def _wait_for_completed(
    transport: MoonrakerStartTransport,
    *,
    expected_path: str,
    expected_size: int,
    timeout: float = 15,
) -> JobIdentitySnapshot:
    """Require exact terminal live/history evidence before the fixture-only reset."""
    deadline = asyncio.get_running_loop().time() + timeout
    latest_error = "no observation"
    while asyncio.get_running_loop().time() < deadline:
        try:
            observation = await transport.query()
        except Exception as error:
            latest_error = type(error).__name__
        else:
            latest = observation.latest_job
            if (
                observation.phase is PrinterPhase.COMPLETED
                and observation.filename == expected_path
                and observation.file_position == expected_size
                and latest is not None
                and latest.filename == expected_path
                and latest.status is JobHistoryStatus.COMPLETED
            ):
                return latest
            latest_error = repr(observation)
        await asyncio.sleep(0.1)
    raise RuntimeError(f"fixture did not reach exact completed state: {latest_error}")


def _proxy_request(path: str, *, method: str = "GET") -> dict[str, Any]:
    request = urllib.request.Request(  # noqa: S310 -- fixed fixture origin.
        f"{PROXY_CONTROL}{path}", method=method
    )
    with urllib.request.urlopen(  # noqa: S310 -- fixed fixture origin.
        request, timeout=5
    ) as response:
        if response.status != 200:
            raise RuntimeError("fixture proxy request failed")
        document = json.load(response)
    if not isinstance(document, dict):
        raise RuntimeError("fixture proxy response is malformed")
    return document


def _count(method: str) -> int:
    document = _proxy_request("/stats")
    try:
        value = document["counts"][method]
    except (KeyError, TypeError) as error:
        raise RuntimeError("fixture proxy count is malformed") from error
    if type(value) is not int:
        raise RuntimeError("fixture proxy count is malformed")
    return value


def _arm(operation: str) -> None:
    _require(
        _proxy_request(f"/arm/{operation}", method="POST") == {"status": "armed"},
        "arm failed",
    )


async def _prove_cancellation(coordinator: DispatchCoordinator, archive: bytes) -> None:
    submitted = _request(CANCEL_OPERATION_ID, CANCEL_IDEMPOTENCY_KEY, archive)
    before_upload = _count("server.files.upload")
    entered = asyncio.Event()
    submission = asyncio.create_task(coordinator.submit(GRANT, submitted, _stalled_stream(entered)))
    await asyncio.wait_for(entered.wait(), timeout=10)
    cancelled = await coordinator.cancel(GRANT, submitted.operation_id, submitted.idempotency_key)
    result = await asyncio.wait_for(submission, timeout=10)
    _require(
        result.state is DispatchState.CANCELLED
        and cancelled is not None
        and cancelled.state is DispatchState.CANCELLED,
        "pre-upload cancellation was not durable",
    )
    _require(_count("server.files.upload") == before_upload, "cancelled source reached upload")


async def _main() -> None:
    archive = _archive()
    runtime = await _runtime()
    coordinator = runtime.coordinator
    try:
        await _wait_for_idle(runtime.transport, expected_latest_job=None)
        await _prove_cancellation(coordinator, archive)

        normal = _request(NORMAL_OPERATION_ID, NORMAL_IDEMPOTENCY_KEY, archive)
        wrong_grant = DispatchGrant(principal_id="wrong-printer", printer_uuid=OTHER_PRINTER_UUID)
        denied = await coordinator.submit(wrong_grant, normal, _stream(archive))
        _require(
            denied.failure is not None and denied.failure.code is DispatchFailureCode.ACCESS_DENIED,
            "mismatched grant was accepted",
        )
        stale = normal.model_copy(
            update={
                "operation_id": "10000000-0000-4000-8000-000000000009",
                "idempotency_key": "10000000-0000-4000-8000-000000000010",
                "safety_profile_generation": PROFILE.generation + 1,
            }
        )
        stale_result = await coordinator.submit(GRANT, stale, _stream(archive))
        _require(
            stale_result.failure is not None
            and stale_result.failure.code is DispatchFailureCode.PROFILE_STALE,
            "stale profile was accepted",
        )

        source_mismatch = _request(
            SOURCE_MISMATCH_OPERATION_ID, SOURCE_MISMATCH_IDEMPOTENCY_KEY, archive
        )
        uploads_before_mismatch = _count("server.files.upload")
        actual_mismatch = archive[:-1] + bytes((archive[-1] ^ 1,))
        mismatch_result = await coordinator.submit(GRANT, source_mismatch, _stream(actual_mismatch))
        _require(
            mismatch_result.state is DispatchState.FAILED
            and mismatch_result.failure is not None
            and mismatch_result.failure.code is DispatchFailureCode.SOURCE_INVALID,
            "declared archive digest did not bind the received source bytes",
        )
        _require(
            _count("server.files.upload") == uploads_before_mismatch,
            "source digest mismatch reached upload",
        )

        uploads_before = _count("server.files.upload")
        starts_before = _count("printer.print.start")
        accepted = await coordinator.submit(GRANT, normal, _stream(archive))
        replay = await coordinator.submit(GRANT, normal, _stream(archive))
        _require(
            accepted.state
            in {
                DispatchState.ACCEPTED,
                DispatchState.VERIFIED,
                DispatchState.STARTING,
                DispatchState.PRINTING,
                DispatchState.COMPLETED,
            }
            and accepted.failure is None
            and replay.operation_id == normal.operation_id
            and replay.failure is None,
            "exact duplicate was not replayed",
        )
        substituted = normal.model_copy(update={"archive_sha256": "sha256:" + "0" * 64})
        conflict = await coordinator.submit(GRANT, substituted, _stream(archive))
        _require(
            conflict.failure is not None
            and conflict.failure.code is DispatchFailureCode.OPERATION_CONFLICT,
            "substituted duplicate was not denied",
        )
        _require(
            await coordinator.result(
                DispatchGrant(principal_id="other-principal", printer_uuid=PRINTER_UUID),
                normal.operation_id,
                normal.idempotency_key,
            )
            is None,
            "cross-principal lookup enumerated an operation",
        )
        _require(
            await coordinator.cancel(wrong_grant, normal.operation_id, normal.idempotency_key)
            is None,
            "cross-printer cancellation was accepted",
        )
        printing = await _wait_state(coordinator, normal, DispatchState.PRINTING)
        _require(
            printing.target == TARGET
            and printing.archive_sha256 == normal.archive_sha256
            and printing.archive_size_bytes == len(archive)
            and printing.selected_gcode_sha256 == f"sha256:{hashlib.sha256(GCODE).hexdigest()}"
            and printing.remote_path == f"klove/{normal.operation_id}.gcode",
            "accepted dispatch lost its exact target or byte binding",
        )
        _require(_count("server.files.upload") == uploads_before + 1, "duplicate uploaded twice")
        _require(_count("printer.print.start") == starts_before + 1, "duplicate started twice")
        await _wait_state(coordinator, normal, DispatchState.COMPLETED, timeout=25)
        completed_job = await _wait_for_completed(
            runtime.transport,
            expected_path=f"klove/{normal.operation_id}.gcode",
            expected_size=len(GCODE),
        )
        await reset_virtual_sd_after_completed_print(runtime.session, _read_api_key())
        await _wait_for_idle(
            runtime.transport,
            expected_latest_job=completed_job,
        )

        ambiguous = _request(AMBIGUOUS_OPERATION_ID, AMBIGUOUS_IDEMPOTENCY_KEY, archive)
        starts_before = _count("printer.print.start")
        _arm("start")
        await coordinator.submit(GRANT, ambiguous, _stream(archive))
        unknown = await _wait_persisted_state(
            runtime.journal, ambiguous, DispatchState.OUTCOME_UNKNOWN
        )
        _require(
            unknown.failure is not None
            and unknown.failure.code is DispatchFailureCode.START_AMBIGUOUS,
            "dropped start response was not fenced",
        )
        _require(
            _count("printer.print.start") == starts_before + 1,
            "ambiguous start was not dispatched exactly once",
        )
        print("native dispatch contract passed", flush=True)
    finally:
        await runtime.close()


if __name__ == "__main__":
    asyncio.run(_main())
