from __future__ import annotations

import copy
import hashlib
import json
from collections.abc import AsyncIterator
from decimal import Decimal
from io import BytesIO
from pathlib import Path

import aiohttp
import pytest
from aiohttp import web
from aiohttp.test_utils import TestServer
from multidict import CIMultiDict
from pydantic import ValidationError

from klove.adapters.moonraker.upload import (
    MoonrakerUploadTransport,
    _decimal,
    _decode_metadata,
    _decode_upload,
    _integer,
    _json_document,
)
from klove.config import PrinterConfig
from klove.domain.upload import MoonrakerGcodeMetadata
from klove.errors import UploadTransportError

API_KEY = "m" * 32
PATH = "klove/22222222-2222-4222-8222-222222222222.gcode"
DATA = b"; generated by OrcaSlicer 2.3.0\nG28\nG1 X1 Y2\n"
DIGEST = "sha256:" + hashlib.sha256(DATA).hexdigest()
MODIFIED = 1_700_000_000.25


def config(endpoint: str) -> PrinterConfig:
    return PrinterConfig(
        id="voron",
        uuid="11111111-1111-4111-8111-111111111111",
        endpoint=endpoint,
        api_key_file=Path("unused"),
        allow_insecure_http=True,
    )


def upload_document(**updates: object) -> dict[str, object]:
    document: dict[str, object] = {
        "item": {
            "root": "gcodes",
            "path": PATH,
            "modified": Decimal(str(MODIFIED)),
            "size": len(DATA),
            "permissions": "rw",
        },
        "print_started": False,
        "print_queued": False,
        "action": "create_file",
    }
    document.update(updates)
    return document


def metadata_result(**updates: object) -> dict[str, object]:
    result: dict[str, object] = {
        "filename": PATH,
        "size": len(DATA),
        "modified": Decimal(str(MODIFIED)),
        "uuid": "44444444-4444-4444-8444-444444444444",
        "file_processors": [],
        "slicer": "OrcaSlicer",
        "nozzle_diameter": Decimal("0.4"),
        "gcode_start_byte": 1,
        "gcode_end_byte": len(DATA),
    }
    result.update(updates)
    return result


@pytest.mark.asyncio
async def test_transport_uses_exact_non_actuating_upload_and_verifies_remote_bytes() -> None:
    observed: dict[str, object] = {}

    async def upload(request: web.Request) -> web.Response:
        assert request.headers["X-Api-Key"] == API_KEY
        fields: dict[str, object] = {}
        reader = await request.multipart()
        while part := await reader.next():
            assert isinstance(part, aiohttp.BodyPartReader)
            if part.name == "file":
                fields["file"] = await part.read()
                fields["filename"] = part.filename
                fields["file_content_type"] = part.headers["Content-Type"]
            else:
                fields[str(part.name)] = await part.text()
        observed["upload"] = fields
        response_document = upload_document()
        response_document["item"] = {
            **copy.deepcopy(response_document["item"]),  # type: ignore[arg-type]
            "modified": MODIFIED,
        }
        return web.json_response(
            response_document,
            status=201,
            headers={"Location": f"/server/files/gcodes/{PATH}"},
        )

    async def metadata(request: web.Request) -> web.Response:
        assert request.headers["X-Api-Key"] == API_KEY
        observed["metadata_filename"] = request.query.getall("filename")
        result = metadata_result()
        result["modified"] = MODIFIED
        result["nozzle_diameter"] = 0.4
        return web.json_response({"result": result})

    async def download(request: web.Request) -> web.Response:
        assert request.headers["X-Api-Key"] == API_KEY
        observed["download_path"] = request.path
        return web.Response(body=DATA, content_type="application/octet-stream")

    application = web.Application()
    application.router.add_post("/server/files/upload", upload)
    application.router.add_get("/server/files/metadata", metadata)
    application.router.add_get(f"/server/files/gcodes/{PATH}", download)
    async with TestServer(application) as server, aiohttp.ClientSession() as session:
        transport = MoonrakerUploadTransport(
            config(str(server.make_url(""))),
            API_KEY,
            session,
            request_timeout_seconds=1,
        )
        receipt = await transport.upload(PATH, BytesIO(DATA), DIGEST, len(DATA))
        metadata_value = await transport.metadata(PATH)
        remote = await transport.download(PATH, len(DATA))

    assert receipt.path == PATH
    assert receipt.modified == Decimal(str(MODIFIED))
    assert metadata_value == MoonrakerGcodeMetadata(
        path=PATH,
        size_bytes=len(DATA),
        modified=Decimal(str(MODIFIED)),
        metadata_uuid="44444444-4444-4444-8444-444444444444",
        file_processors=(),
        nozzle_diameter_micrometres=400,
        gcode_start_byte=1,
        gcode_end_byte=len(DATA),
        job_id=None,
        print_start_time=None,
    )
    assert remote.size_bytes == len(DATA)
    assert remote.sha256 == DIGEST
    assert observed == {
        "upload": {
            "root": "gcodes",
            "path": "klove",
            "checksum": DIGEST.removeprefix("sha256:"),
            "print": "false",
            "file": DATA,
            "filename": PATH.removeprefix("klove/"),
            "file_content_type": "application/octet-stream",
        },
        "metadata_filename": [PATH],
        "download_path": f"/server/files/gcodes/{PATH}",
    }


@pytest.mark.asyncio
async def test_metadata_404_is_the_only_not_ready_result() -> None:
    async def metadata(_request: web.Request) -> web.Response:
        return web.Response(status=404)

    application = web.Application()
    application.router.add_get("/server/files/metadata", metadata)
    async with TestServer(application) as server, aiohttp.ClientSession() as session:
        transport = MoonrakerUploadTransport(
            config(str(server.make_url(""))), API_KEY, session, request_timeout_seconds=1
        )
        assert await transport.metadata(PATH) is None


@pytest.mark.parametrize(
    "document",
    [
        [],
        {},
        {**upload_document(), "extra": True},
        {**upload_document(), "item": []},
        {
            **upload_document(),
            "item": {**upload_document()["item"], "extra": True},  # type: ignore[dict-item]
        },
        {**upload_document(), "print_started": True},
        {**upload_document(), "print_queued": True},
        {**upload_document(), "action": "move_file"},
        {
            **upload_document(),
            "item": {**upload_document()["item"], "root": "config"},  # type: ignore[dict-item]
        },
        {
            **upload_document(),
            "item": {**upload_document()["item"], "permissions": "r"},  # type: ignore[dict-item]
        },
        {
            **upload_document(),
            "item": {**upload_document()["item"], "path": 1},  # type: ignore[dict-item]
        },
    ],
)
def test_upload_response_rejects_every_malformed_or_actuating_shape(document: object) -> None:
    with pytest.raises(UploadTransportError):
        _decode_upload(document)


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("path", "bad.gcode"),
        ("size", True),
        ("size", 0),
        ("modified", True),
        ("modified", Decimal("NaN")),
        ("modified", Decimal("0")),
    ],
)
def test_upload_response_rejects_invalid_item_values(field: str, value: object) -> None:
    document = upload_document()
    item = copy.deepcopy(document["item"])
    assert isinstance(item, dict)
    item[field] = value
    document["item"] = item
    with pytest.raises((UploadTransportError, ValidationError)):
        _decode_upload(document)


def test_metadata_decoder_accepts_only_exact_safety_evidence() -> None:
    decoded = _decode_metadata({"result": metadata_result()}, PATH)
    assert decoded.nozzle_diameter_micrometres == 400
    assert decoded.job_id is None

    invalid: list[object] = [
        [],
        {},
        {"result": metadata_result(), "extra": True},
        {"result": []},
        {"result": {"filename": PATH}},
    ]
    for document in invalid:
        with pytest.raises(UploadTransportError):
            _decode_metadata(document, PATH)


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("filename", "other.gcode"),
        ("uuid", 1),
        ("uuid", "not-a-uuid"),
        ("file_processors", "none"),
        ("file_processors", [1]),
        ("job_id", "000001"),
        ("print_start_time", 1),
        ("nozzle_diameter", Decimal("0.4001")),
        ("size", True),
        ("modified", "1"),
        ("gcode_start_byte", True),
        ("gcode_end_byte", len(DATA) + 1),
    ],
)
def test_metadata_decoder_rejects_missing_ambiguous_or_malformed_fields(
    field: str, value: object
) -> None:
    result = metadata_result(**{field: value})
    with pytest.raises((UploadTransportError, ValidationError)):
        _decode_metadata({"result": result}, PATH)


class FakeContent:
    def __init__(self, chunks: list[bytes]) -> None:
        self._chunks = chunks

    async def iter_chunked(self, _size: int) -> AsyncIterator[bytes]:
        for chunk in self._chunks:
            yield chunk


class FakeResponse:
    def __init__(  # noqa: PLR0913 -- explicit HTTP response test dimensions.
        self,
        body: bytes = b'{"result":{}}',
        *,
        status: int = 200,
        content_types: list[str] | None = None,
        parsed_content_type: str = "application/json",
        charset: str | None = None,
        content_length: str | None = None,
        chunks: list[bytes] | None = None,
    ) -> None:
        headers: list[tuple[str, str]] = [
            ("Content-Type", value)
            for value in (content_types if content_types is not None else ["application/json"])
        ]
        if content_length is not None:
            headers.append(("Content-Length", content_length))
        self.status = status
        self.headers = CIMultiDict(headers)
        self.content_type = parsed_content_type
        self.charset = charset
        self.content = FakeContent(chunks if chunks is not None else [body])


@pytest.mark.asyncio
async def test_json_response_is_bounded_unique_finite_utf8() -> None:
    assert await _json_document(FakeResponse(), expected_status=200) == {"result": {}}  # type: ignore[arg-type]
    invalid = (
        FakeResponse(status=500),
        FakeResponse(content_types=[]),
        FakeResponse(content_types=["application/json", "application/json"]),
        FakeResponse(parsed_content_type="text/plain"),
        FakeResponse(charset="iso-8859-1"),
        FakeResponse(body=b"x" * (64 * 1024 + 1)),
        FakeResponse(body=b"\xff"),
        FakeResponse(body=b'{"a":1,"a":2}'),
        FakeResponse(body=b'{"a":NaN}'),
    )
    for response in invalid:
        with pytest.raises(UploadTransportError):
            await _json_document(response, expected_status=200)  # type: ignore[arg-type]


def test_numeric_decoders_reject_bool_text_and_non_finite_values() -> None:
    assert _integer(1) == 1
    assert _decimal(1) == Decimal(1)
    assert _decimal(Decimal("1.25")) == Decimal("1.25")
    for value in (True, Decimal("1.0"), "1"):
        with pytest.raises(UploadTransportError):
            _integer(value)
    for value in (True, "1", Decimal("Infinity")):
        with pytest.raises(UploadTransportError):
            _decimal(value)


class FakeContext:
    def __init__(self, response: FakeResponse) -> None:
        self.response = response

    async def __aenter__(self) -> FakeResponse:
        return self.response

    async def __aexit__(self, *_args: object) -> None:
        return None


class FakeSession:
    def __init__(self, response: FakeResponse | None = None, *, broken: bool = False) -> None:
        self.response = response
        self.broken = broken

    def post(self, *_args: object, **_kwargs: object) -> FakeContext:
        if self.broken:
            raise aiohttp.ClientError("secret remote detail")
        assert self.response is not None
        return FakeContext(self.response)

    def get(self, *_args: object, **_kwargs: object) -> FakeContext:
        if self.broken:
            raise aiohttp.ClientError("secret remote detail")
        assert self.response is not None
        return FakeContext(self.response)


@pytest.mark.asyncio
async def test_public_methods_reject_invalid_paths_and_bound_client_errors() -> None:
    transport = MoonrakerUploadTransport(
        config("http://127.0.0.1:7125"),
        API_KEY,
        FakeSession(broken=True),  # type: ignore[arg-type]
        request_timeout_seconds=1,
    )
    for operation in (
        transport.upload(PATH, BytesIO(DATA), DIGEST, len(DATA)),
        transport.metadata(PATH),
        transport.download(PATH, len(DATA)),
    ):
        with pytest.raises(UploadTransportError):
            await operation

    for operation in (
        transport.upload("bad.gcode", BytesIO(DATA), DIGEST, len(DATA)),
        transport.metadata("bad.gcode"),
        transport.download("bad.gcode", len(DATA)),
    ):
        with pytest.raises(UploadTransportError):
            await operation


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "response",
    [
        FakeResponse(status=500, content_length=str(len(DATA)), chunks=[DATA]),
        FakeResponse(content_length=str(len(DATA) + 1), chunks=[DATA]),
        FakeResponse(content_length=str(len(DATA)), chunks=[DATA + b"x"]),
        FakeResponse(content_length=str(len(DATA)), chunks=[DATA[:-1]]),
    ],
)
async def test_download_rejects_status_length_overflow_and_truncation(
    response: FakeResponse,
) -> None:
    transport = MoonrakerUploadTransport(
        config("http://127.0.0.1:7125"),
        API_KEY,
        FakeSession(response),  # type: ignore[arg-type]
        request_timeout_seconds=1,
    )
    with pytest.raises(UploadTransportError):
        await transport.download(PATH, len(DATA))


@pytest.mark.asyncio
async def test_metadata_non_404_status_and_upload_location_or_identity_mismatch_fail() -> None:
    metadata_transport = MoonrakerUploadTransport(
        config("http://127.0.0.1:7125"),
        API_KEY,
        FakeSession(FakeResponse(status=500)),  # type: ignore[arg-type]
        request_timeout_seconds=1,
    )
    with pytest.raises(UploadTransportError):
        await metadata_transport.metadata(PATH)

    body = json.dumps(
        {
            "item": {
                "root": "gcodes",
                "path": PATH,
                "modified": MODIFIED,
                "size": len(DATA) + 1,
                "permissions": "rw",
            },
            "print_started": False,
            "print_queued": False,
            "action": "create_file",
        }
    ).encode()
    upload_response = FakeResponse(body=body, status=201)
    upload_response.headers.add("Location", f"/server/files/gcodes/{PATH}")
    upload_transport = MoonrakerUploadTransport(
        config("http://127.0.0.1:7125"),
        API_KEY,
        FakeSession(upload_response),  # type: ignore[arg-type]
        request_timeout_seconds=1,
    )
    with pytest.raises(UploadTransportError):
        await upload_transport.upload(PATH, BytesIO(DATA), DIGEST, len(DATA))

    location_response = FakeResponse(body=body, status=201)
    location_response.headers.add("Location", "/wrong")
    location_transport = MoonrakerUploadTransport(
        config("http://127.0.0.1:7125"),
        API_KEY,
        FakeSession(location_response),  # type: ignore[arg-type]
        request_timeout_seconds=1,
    )
    with pytest.raises(UploadTransportError):
        await location_transport.upload(PATH, BytesIO(DATA), DIGEST, len(DATA))
