from __future__ import annotations

import asyncio
import hashlib
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from decimal import Decimal
from io import BytesIO
from pathlib import Path
from typing import BinaryIO, cast
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo

import pytest

from klove.domain.artifacts import (
    ArtifactLimits,
    ArtifactOperationState,
    PlateSelection,
    target_for_safety_profile,
)
from klove.domain.dispatch import (
    DispatchFailure,
    DispatchFailureCode,
    DispatchGrant,
    DispatchJournalRecord,
    DispatchRequest,
    DispatchState,
)
from klove.domain.models import JobHistoryStatus, JobIdentitySnapshot, PrinterPhase
from klove.domain.onboarding import RegisteredPrinter
from klove.domain.start import (
    StartBoundary,
    StartConfirmation,
    StartFailure,
    StartFailureCode,
    StartObservation,
    StartOperationResult,
    StartState,
)
from klove.domain.upload import (
    MoonrakerGcodeMetadata,
    MoonrakerUploadReceipt,
    RemoteFileDigest,
    UploadState,
)
from klove.errors import JournalError, StartTransportError, UploadTransportError
from klove.orchestration.admission import PrinterAdmissionGates
from klove.orchestration.dispatch import (
    DispatchCoordinator,
    DispatchReceiveLimiter,
    _needs_start_reconciliation,
    _observation_matches_confirmation,
    _phase_for_history,
    _receive_was_cancelled,
    _ReceivingOperation,
    _wait_for_receiving,
)
from klove.orchestration.start import StartService
from klove.orchestration.upload import UploadService
from klove.persistence.dispatch_journal import (
    DispatchJournal,
    DispatchJournalCapacityError,
    DispatchJournalFenceError,
)
from klove.persistence.dispatch_spool import DispatchSpool, DispatchSpoolError
from klove.persistence.start_journal import StartJournal

from ..onboarding_helpers import printer as registered_printer
from ..start_helpers import (
    PRINTER_UUID,
    history_job,
    printer_config,
    safety_profile,
    verified_upload,
)

GCODE = b"; generated by OrcaSlicer 2.3.0\nG28\nG1 X1 Y2\n"
SELECTED_PATH = "Metadata/plate_1.gcode"
OPERATION_ID = "22222222-2222-4222-8222-222222222222"
IDEMPOTENCY_KEY = "33333333-3333-4333-8333-333333333333"
ARCHIVE_TIMESTAMP = (2020, 1, 1, 0, 0, 0)


def archive() -> bytes:
    target = BytesIO()
    with ZipFile(target, mode="w", compression=ZIP_DEFLATED) as bundle:
        for path, content in (
            ("[Content_Types].xml", b"<Types/>"),
            ("_rels/.rels", b"<Relationships/>"),
            ("3D/3dmodel.model", b"<model/>"),
            (SELECTED_PATH, GCODE),
        ):
            member = ZipInfo(path, date_time=ARCHIVE_TIMESTAMP)
            member.compress_type = ZIP_DEFLATED
            bundle.writestr(member, content)
    return target.getvalue()


async def stream(data: bytes) -> AsyncIterator[bytes]:
    yield data


def request(payload: bytes, **updates: object) -> DispatchRequest:
    target = target_for_safety_profile(safety_profile())
    values: dict[str, object] = {
        "operation_id": OPERATION_ID,
        "idempotency_key": IDEMPOTENCY_KEY,
        "printer_uuid": target.printer_uuid,
        "slicer_profile_id": target.slicer_profile_id,
        "safety_profile_generation": target.safety_profile_generation,
        "safety_profile_fingerprint": target.safety_profile_fingerprint,
        "selected_plate": PlateSelection(plate_id="1", archive_path=SELECTED_PATH),
        "archive_sha256": "sha256:" + hashlib.sha256(payload).hexdigest(),
        "archive_size_bytes": len(payload),
    }
    values.update(updates)
    return DispatchRequest.model_validate(values)


def grant(*, principal: str = "grove-worker") -> DispatchGrant:
    return DispatchGrant(principal_id=principal, printer_uuid=PRINTER_UUID)


def durable(submitted: DispatchRequest, state: DispatchState) -> DispatchJournalRecord:
    return DispatchJournalRecord(grant=grant(), request=submitted, state=state)


def test_archive_is_byte_identical_across_clock_changes(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr("zipfile.time.localtime", lambda _value: (2020, 1, 1, 0, 0, 0))
    first = archive()
    monkeypatch.setattr("zipfile.time.localtime", lambda _value: (2020, 1, 1, 0, 0, 2))

    assert first == archive()


@pytest.mark.parametrize("capacity", [True, 0, 65])
def test_receive_limiter_rejects_non_integer_or_out_of_bound_capacity(capacity: object) -> None:
    with pytest.raises(ValueError):
        DispatchReceiveLimiter(capacity)  # type: ignore[arg-type]


def test_receive_limiter_is_nonwaiting_and_detects_overrelease() -> None:
    limiter = DispatchReceiveLimiter(1)

    assert limiter.try_acquire() is True
    assert limiter.try_acquire() is False
    limiter.release()
    with pytest.raises(RuntimeError, match="too many"):
        limiter.release()


@pytest.mark.asyncio
async def test_dispatch_helper_predicates_cover_exact_job_and_history_variants() -> None:
    submitted = request(archive())
    receiving = _ReceivingOperation()
    assert _receive_was_cancelled(receiving) is False
    receiving.cancelled.set()
    assert _receive_was_cancelled(receiving) is True
    assert await _wait_for_receiving(None) is False
    ready = asyncio.Event()
    ready.set()
    assert await _wait_for_receiving(ready) is True
    assert _needs_start_reconciliation(durable(submitted, DispatchState.ACCEPTED)) is False
    assert (
        _needs_start_reconciliation(
            DispatchJournalRecord(
                grant=grant(),
                request=submitted,
                state=DispatchState.OUTCOME_UNKNOWN,
                failure=DispatchFailure(code=DispatchFailureCode.START_AMBIGUOUS),
            )
        )
        is False
    )
    confirmation = StartConfirmation(
        path=f"klove/{submitted.operation_id}.gcode",
        eventtime=1,
        phase=PrinterPhase.PRINTING,
        file_position=1,
        job=history_job(
            filename=f"klove/{submitted.operation_id}.gcode",
            status=JobHistoryStatus.IN_PROGRESS,
        ),
    )
    matching = StartObservation(
        eventtime=2,
        phase=PrinterPhase.PRINTING,
        filename=confirmation.path,
        file_position=2,
        latest_job=confirmation.job,
    )
    assert _observation_matches_confirmation(matching, confirmation) is True
    assert (
        _observation_matches_confirmation(
            matching.model_copy(
                update={"latest_job": None, "phase": PrinterPhase.IDLE, "filename": ""}
            ),
            confirmation,
        )
        is False
    )
    assert _phase_for_history(JobHistoryStatus.COMPLETED) is PrinterPhase.COMPLETED
    assert _phase_for_history(JobHistoryStatus.CANCELLED) is PrinterPhase.CANCELLED
    assert _phase_for_history(JobHistoryStatus.ERROR) is PrinterPhase.ERROR


class Registry:
    def __init__(self) -> None:
        self.record = registered_printer(safety_profiles=(safety_profile(),))

    def get(self, printer_uuid: str) -> RegisteredPrinter | None:
        return self.record if printer_uuid == self.record.printer_uuid else None


class InMemoryJournal:
    def __init__(self, current: DispatchJournalRecord | None, *, failure: bool = False) -> None:
        self.current = current
        self.failure = failure

    def lookup(self, _operation_id: str, _idempotency_key: str) -> DispatchJournalRecord | None:
        if self.failure:
            raise JournalError
        return self.current

    def initialize(self) -> None:
        if self.failure:
            raise JournalError

    def records(self) -> tuple[DispatchJournalRecord, ...]:
        if self.failure:
            raise JournalError
        return () if self.current is None else (self.current,)

    def replace(
        self, expected: DispatchJournalRecord, updated: DispatchJournalRecord
    ) -> DispatchJournalRecord:
        if self.failure:
            raise JournalError
        assert self.current == expected
        self.current = updated
        return updated


def install_journal(coordinator: DispatchCoordinator, journal: object) -> None:
    """Install a deliberately narrow journal double without widening production types."""
    coordinator._journal = cast(DispatchJournal, journal)


class Remote:
    def __init__(self) -> None:
        self.files: dict[str, tuple[bytes, MoonrakerGcodeMetadata]] = {}
        self.uploads: list[str] = []
        self.dispatches: list[str] = []
        self.fail_upload = False
        self.fail_queries = False
        self.fail_after_query: int | None = None
        self.query_count = 0
        self.query_entered = asyncio.Event()
        self.release_query = asyncio.Event()
        self.release_query.set()
        self.status = JobHistoryStatus.IN_PROGRESS
        self.upload_entered = asyncio.Event()
        self.release_upload = asyncio.Event()
        self.release_upload.set()

    async def upload(
        self, path: str, content: BinaryIO, sha256: str, size_bytes: int
    ) -> MoonrakerUploadReceipt:
        self.upload_entered.set()
        await self.release_upload.wait()
        if self.fail_upload:
            raise UploadTransportError
        data = content.read()
        assert len(data) == size_bytes
        assert sha256 == "sha256:" + hashlib.sha256(data).hexdigest()
        modified = Decimal("1700000000.25")
        metadata = MoonrakerGcodeMetadata(
            path=path,
            size_bytes=len(data),
            modified=modified,
            metadata_uuid="44444444-4444-4444-8444-444444444444",
            file_processors=(),
            nozzle_diameter_micrometres=400,
            gcode_start_byte=1,
            gcode_end_byte=len(data),
            job_id=None,
            print_start_time=None,
        )
        self.files[path] = (data, metadata)
        self.uploads.append(path)
        return MoonrakerUploadReceipt(path=path, size_bytes=len(data), modified=modified)

    async def metadata(self, path: str) -> MoonrakerGcodeMetadata | None:
        file = self.files.get(path)
        return None if file is None else file[1]

    async def download(self, path: str, expected_size: int) -> RemoteFileDigest:
        data, _metadata = self.files[path]
        assert len(data) == expected_size
        return RemoteFileDigest(
            size_bytes=len(data), sha256="sha256:" + hashlib.sha256(data).hexdigest()
        )

    async def query(self) -> StartObservation:
        self.query_count += 1
        self.query_entered.set()
        await self.release_query.wait()
        if self.fail_queries and self.dispatches:
            raise StartTransportError
        if self.fail_after_query is not None and self.query_count > self.fail_after_query:
            raise StartTransportError
        if not self.dispatches:
            return StartObservation(
                eventtime=10,
                phase=PrinterPhase.IDLE,
                filename="",
                file_position=0,
                latest_job=None,
            )
        path = self.dispatches[-1]
        phase = (
            PrinterPhase.PRINTING
            if self.status is JobHistoryStatus.IN_PROGRESS
            else PrinterPhase.COMPLETED
            if self.status is JobHistoryStatus.COMPLETED
            else PrinterPhase.CANCELLED
            if self.status is JobHistoryStatus.CANCELLED
            else PrinterPhase.ERROR
        )
        return StartObservation(
            eventtime=11,
            phase=phase,
            filename=path,
            file_position=10,
            latest_job=JobIdentitySnapshot(
                job_id="000002",
                filename=path,
                start_time=1_700_000_100,
                status=self.status,
            ),
        )

    async def dispatch(self, path: str) -> None:
        self.dispatches.append(path)


async def eventually(
    coordinator: DispatchCoordinator,
    submitted: DispatchRequest,
    *,
    expected: DispatchState,
) -> None:
    for _ in range(100):
        result = await coordinator.result(
            grant(), submitted.operation_id, submitted.idempotency_key
        )
        if result is not None and result.state is expected:
            return
        await asyncio.sleep(0)
    pytest.fail(f"operation did not reach {expected.value}")


async def coordinator(
    tmp_path: Path,
    remote: Remote,
    registry: Registry | None = None,
    *,
    receive_timeout_seconds: float = 300.0,
    receive_limiter: DispatchReceiveLimiter | None = None,
) -> tuple[DispatchCoordinator, PrinterAdmissionGates]:
    state = tmp_path / "state"
    state.mkdir(mode=0o700)
    state.chmod(0o700)
    admissions = PrinterAdmissionGates()
    limits = ArtifactLimits(metadata_wait_seconds=0.1, metadata_poll_interval_seconds=0.01)
    uploader = UploadService(printer_config(), remote, limits=limits, admissions=admissions)
    starter = StartService(
        printer_config(),
        remote,
        StartJournal(state / "start.sqlite3"),
        enabled=True,
        confirmation_timeout_seconds=0.1,
        poll_interval_seconds=0.01,
        admissions=admissions,
    )
    await starter.initialize()
    value = DispatchCoordinator(
        PRINTER_UUID,
        registry or Registry(),
        uploader,
        starter,
        DispatchJournal(state / "dispatch.sqlite3"),
        DispatchSpool(state / "spool", limits=limits),
        limits=limits,
        operation_capacity=8,
        admissions=admissions,
        receive_limiter=receive_limiter or DispatchReceiveLimiter(4),
        receive_timeout_seconds=receive_timeout_seconds,
    )
    spool = state / "spool"
    spool.mkdir(mode=0o700)
    spool.chmod(0o700)
    await value.initialize()
    return value, admissions


@pytest.mark.asyncio
async def test_coordinator_rejects_out_of_bound_durable_or_receive_limits(tmp_path: Path) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())

    with pytest.raises(ValueError):
        DispatchCoordinator(
            PRINTER_UUID,
            value._registry,
            value._uploader,
            value._starter,
            value._journal,
            value._spool,
            limits=value._limits,
            operation_capacity=0,
            admissions=value._admissions,
            receive_limiter=DispatchReceiveLimiter(1),
        )
    with pytest.raises(ValueError):
        DispatchCoordinator(
            PRINTER_UUID,
            value._registry,
            value._uploader,
            value._starter,
            value._journal,
            value._spool,
            limits=value._limits,
            operation_capacity=1,
            admissions=value._admissions,
            receive_limiter=DispatchReceiveLimiter(1),
            receive_timeout_seconds=0,
        )
    with pytest.raises(ValueError):
        DispatchCoordinator(
            PRINTER_UUID,
            value._registry,
            value._uploader,
            value._starter,
            value._journal,
            value._spool,
            limits=value._limits,
            operation_capacity=True,
            admissions=value._admissions,
            receive_limiter=DispatchReceiveLimiter(1),
        )
    with pytest.raises(ValueError):
        DispatchCoordinator(
            PRINTER_UUID,
            value._registry,
            value._uploader,
            value._starter,
            value._journal,
            value._spool,
            limits=value._limits,
            operation_capacity=1,
            admissions=value._admissions,
            receive_limiter=DispatchReceiveLimiter(1),
            receive_timeout_seconds=float("nan"),
        )


@pytest.mark.asyncio
async def test_result_reconcile_and_cancel_are_non_enumerating_on_lookup_failure(
    tmp_path: Path,
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())
    install_journal(
        value, InMemoryJournal(durable(submitted, DispatchState.RECEIVING), failure=True)
    )

    assert await value.result(grant(), submitted.operation_id, submitted.idempotency_key) is None
    assert await value.reconcile(grant(), submitted.operation_id, submitted.idempotency_key) is None
    assert await value.cancel(grant(), submitted.operation_id, submitted.idempotency_key) is None
    assert (
        await value.cancel(
            DispatchGrant(
                principal_id="grove-worker",
                printer_uuid="55555555-5555-4555-8555-555555555555",
            ),
            submitted.operation_id,
            submitted.idempotency_key,
        )
        is None
    )


@pytest.mark.asyncio
async def test_result_and_cancel_bind_grant_and_cover_all_pre_start_states(tmp_path: Path) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())
    journal = InMemoryJournal(durable(submitted, DispatchState.RECEIVING))
    install_journal(value, journal)

    assert (
        await value.result(
            grant(principal="other"), submitted.operation_id, submitted.idempotency_key
        )
        is None
    )
    cancelled = await value.cancel(grant(), submitted.operation_id, submitted.idempotency_key)
    assert cancelled is not None and cancelled.state is DispatchState.CANCELLED
    journal.current = DispatchJournalRecord(
        grant=grant(),
        request=submitted,
        state=DispatchState.FAILED,
        failure=DispatchFailure(code=DispatchFailureCode.SOURCE_INVALID),
    )
    started = await value.cancel(grant(), submitted.operation_id, submitted.idempotency_key)
    assert started is not None and started.state is DispatchState.FAILED
    journal.current = durable(submitted, DispatchState.ACCEPTED)
    journal.failure = True
    assert await value.cancel(grant(), submitted.operation_id, submitted.idempotency_key) is None


@pytest.mark.asyncio
async def test_result_and_cancel_do_not_accept_a_partial_durable_identity(tmp_path: Path) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())
    value._journal.reserve(durable(submitted, DispatchState.RECEIVING), capacity=8)
    wrong_key = "55555555-5555-4555-8555-555555555555"

    assert await value.result(grant(), submitted.operation_id, wrong_key) is None
    assert await value.cancel(grant(), submitted.operation_id, wrong_key) is None


@pytest.mark.asyncio
async def test_cancel_hides_storage_failures_and_requires_a_live_receipt_owner(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())

    class FailingReplaceJournal:
        def __init__(self, current: DispatchJournalRecord) -> None:
            self.current = current

        def lookup(self, _operation_id: str, _idempotency_key: str) -> DispatchJournalRecord:
            return self.current

        def replace(
            self, _expected: DispatchJournalRecord, _updated: DispatchJournalRecord
        ) -> DispatchJournalRecord:
            raise JournalError

    install_journal(value, FailingReplaceJournal(durable(submitted, DispatchState.RECEIVING)))
    assert await value.cancel(grant(), submitted.operation_id, submitted.idempotency_key) is None
    install_journal(value, FailingReplaceJournal(durable(submitted, DispatchState.ACCEPTED)))
    assert await value.cancel(grant(), submitted.operation_id, submitted.idempotency_key) is None

    receiving = _ReceivingOperation()
    value._receiving[(submitted.operation_id, submitted.idempotency_key)] = receiving
    install_journal(value, InMemoryJournal(durable(submitted, DispatchState.RECEIVING)))

    async def wait_false(_done: asyncio.Event | None) -> bool:
        return False

    monkeypatch.setattr("klove.orchestration.dispatch._wait_for_receiving", wait_false)
    assert await value.cancel(grant(), submitted.operation_id, submitted.idempotency_key) is None


@pytest.mark.asyncio
async def test_cancel_hides_post_receipt_lookup_failure_or_changed_record(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())
    receiving = _ReceivingOperation()
    value._receiving[(submitted.operation_id, submitted.idempotency_key)] = receiving

    async def wait_true(_done: asyncio.Event | None) -> bool:
        return True

    monkeypatch.setattr("klove.orchestration.dispatch._wait_for_receiving", wait_true)

    class SequenceJournal:
        def __init__(self, second: DispatchJournalRecord | Exception | None) -> None:
            self.calls = 0
            self.second = second

        def lookup(self, _operation_id: str, _idempotency_key: str) -> DispatchJournalRecord | None:
            self.calls += 1
            if self.calls == 1:
                return durable(submitted, DispatchState.RECEIVING)
            if isinstance(self.second, Exception):
                raise self.second
            return self.second

    install_journal(value, SequenceJournal(JournalError()))
    assert await value.cancel(grant(), submitted.operation_id, submitted.idempotency_key) is None
    install_journal(value, SequenceJournal(None))
    assert await value.cancel(grant(), submitted.operation_id, submitted.idempotency_key) is None


@pytest.mark.asyncio
async def test_result_hides_journal_error_during_reconciliation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())
    printing = durable(submitted, DispatchState.ACCEPTED).model_copy(
        update={"state": DispatchState.PRINTING}
    )
    install_journal(value, InMemoryJournal(printing))

    async def unavailable(_record: DispatchJournalRecord) -> DispatchJournalRecord:
        raise JournalError

    monkeypatch.setattr(value, "_reconcile_printing", unavailable)
    assert await value.result(grant(), submitted.operation_id, submitted.idempotency_key) is None


@pytest.mark.asyncio
async def test_initialize_fails_closed_and_only_schedules_safe_own_continuations(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())

    class BrokenJournal:
        def initialize(self) -> None:
            raise JournalError

    install_journal(value, BrokenJournal())
    await value.initialize()
    assert value._ready is False

    class ReconciliationSpool:
        def initialize(self) -> None:
            return None

        def operation_ids(self) -> frozenset[str]:
            return frozenset()

        def verify(self, _request: DispatchRequest) -> None:
            return None

        def remove(self, _request: DispatchRequest) -> None:
            return None

    value._spool = ReconciliationSpool()  # type: ignore[assignment]

    own = durable(submitted, DispatchState.ACCEPTED)
    foreign_request = submitted.model_copy(
        update={"printer_uuid": "55555555-5555-4555-8555-555555555555"}
    )
    foreign = DispatchJournalRecord(
        grant=DispatchGrant(principal_id="grove-worker", printer_uuid=foreign_request.printer_uuid),
        request=foreign_request,
        state=DispatchState.ACCEPTED,
    )

    class RecoveringJournal:
        def initialize(self) -> None:
            return None

        def records(self) -> tuple[DispatchJournalRecord, ...]:
            return foreign, own

    scheduled: list[DispatchJournalRecord] = []

    async def schedule(record: DispatchJournalRecord) -> None:
        scheduled.append(record)

    install_journal(value, RecoveringJournal())
    monkeypatch.setattr(value, "_recover_record", lambda record: record)
    monkeypatch.setattr(value, "_schedule", schedule)
    await value.initialize()

    assert bool(value._ready)
    assert scheduled == [own]

    printing = own.model_copy(update={"state": DispatchState.PRINTING})
    starting = own.model_copy(update={"state": DispatchState.STARTING})
    terminal = DispatchJournalRecord(
        grant=grant(),
        request=submitted,
        state=DispatchState.FAILED,
        failure=DispatchFailure(code=DispatchFailureCode.SOURCE_INVALID),
    )

    class ReconcileJournal:
        def initialize(self) -> None:
            return None

        def records(self) -> tuple[DispatchJournalRecord, ...]:
            return terminal, printing, starting

    reconciled: list[DispatchState] = []

    async def reconcile_printing(record: DispatchJournalRecord) -> DispatchJournalRecord:
        reconciled.append(record.state)
        return own

    async def reconcile_started(
        record: DispatchJournalRecord, *, resume_missing_start: bool
    ) -> DispatchJournalRecord:
        assert resume_missing_start is True
        reconciled.append(record.state)
        return own

    install_journal(value, ReconcileJournal())
    monkeypatch.setattr(value, "_reconcile_printing", reconcile_printing)
    monkeypatch.setattr(value, "_reconcile_started", reconcile_started)
    scheduled.clear()
    await value.initialize()
    assert reconciled == [DispatchState.PRINTING, DispatchState.STARTING]
    assert scheduled == [own, own]

    async def failed_reconcile(_record: DispatchJournalRecord) -> DispatchJournalRecord:
        raise JournalError

    value._ready = True
    monkeypatch.setattr(value, "_reconcile_printing", failed_reconcile)
    await value.initialize()
    assert value._ready is False


@pytest.mark.asyncio
async def test_initialize_rejects_orphan_or_missing_required_spool_evidence(
    tmp_path: Path,
) -> None:
    orphan_root = tmp_path / "orphan"
    orphan_root.mkdir()
    orphan, _admissions = await coordinator(orphan_root, Remote())
    orphan_path = orphan_root / "state" / "spool" / "55555555-5555-4555-8555-555555555555.gcode.3mf"
    orphan_path.write_bytes(b"orphan")
    orphan_path.chmod(0o600)
    await orphan.initialize()
    assert not bool(orphan._ready)

    missing_root = tmp_path / "missing"
    missing_root.mkdir()
    remote = Remote()
    missing, _admissions = await coordinator(missing_root, remote)
    submitted = request(archive())
    await missing.submit(grant(), submitted, stream(archive()))
    await eventually(missing, submitted, expected=DispatchState.PRINTING)
    confirmed = missing._journal.lookup(submitted.operation_id, submitted.idempotency_key)
    assert confirmed is not None
    crashed = confirmed.model_copy(update={"state": DispatchState.STARTING, "start": None})
    install_journal(missing, InMemoryJournal(crashed))
    denied = StartOperationResult(
        operation_id=submitted.operation_id,
        idempotency_key=submitted.idempotency_key,
        state=StartState.DENIED,
        failure=StartFailure(
            boundary=StartBoundary.RECONCILIATION,
            code=StartFailureCode.RECONCILIATION_PENDING,
        ),
    )

    class MissingStartJournal:
        async def reconcile(self, *_args: object, **_kwargs: object) -> StartOperationResult:
            return denied

    missing._starter = MissingStartJournal()  # type: ignore[assignment]
    await missing.initialize()
    assert not bool(missing._ready)


@pytest.mark.asyncio
async def test_initialize_removes_a_known_terminal_spool_leftover(tmp_path: Path) -> None:
    root = tmp_path / "terminal"
    root.mkdir()
    value, _admissions = await coordinator(root, Remote())
    submitted = request(archive())
    value._spool.write(submitted, archive())
    terminal = DispatchJournalRecord(
        grant=grant(),
        request=submitted,
        state=DispatchState.FAILED,
        failure=DispatchFailure(code=DispatchFailureCode.SOURCE_INVALID),
    )
    install_journal(value, InMemoryJournal(terminal))

    await value.initialize()

    assert bool(value._ready)
    assert value._spool.exists(submitted) is False


@pytest.mark.asyncio
@pytest.mark.parametrize(
    ("error", "code"),
    [
        (DispatchJournalCapacityError, DispatchFailureCode.CAPACITY_EXHAUSTED),
        (DispatchJournalFenceError, DispatchFailureCode.PRINTER_FENCED),
        (JournalError, DispatchFailureCode.STORAGE_UNAVAILABLE),
    ],
)
async def test_submit_denies_reservation_failures_without_consuming_source(
    tmp_path: Path,
    error: type[Exception],
    code: DispatchFailureCode,
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())

    class FailingJournal:
        def reserve(
            self, _record: DispatchJournalRecord, *, capacity: int
        ) -> tuple[DispatchJournalRecord, bool]:
            assert capacity == 8
            raise error

    install_journal(value, FailingJournal())
    result = await value.submit(grant(), submitted, stream(archive()))

    assert result.failure is not None and result.failure.code is code


@pytest.mark.asyncio
async def test_submit_denies_unauthorised_unready_and_unavailable_printer(tmp_path: Path) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())
    denied = await value.submit(
        DispatchGrant(
            principal_id="worker",
            printer_uuid="55555555-5555-4555-8555-555555555555",
        ),
        submitted,
        stream(archive()),
    )
    assert denied.failure is not None and denied.failure.code is DispatchFailureCode.ACCESS_DENIED
    value._ready = False
    pending = await value.submit(grant(), submitted, stream(archive()))
    assert pending.failure is not None
    assert pending.failure.code is DispatchFailureCode.RECONCILIATION_PENDING
    value._ready = True

    class MissingRegistry:
        def get(self, _printer_uuid: str) -> None:
            return None

    value._registry = MissingRegistry()
    unavailable = await value.submit(grant(), submitted, stream(archive()))
    assert unavailable.failure is not None
    assert unavailable.failure.code is DispatchFailureCode.PRINTER_UNAVAILABLE


@pytest.mark.asyncio
async def test_submit_replays_exact_duplicate_and_rejects_substituted_duplicate(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())
    existing = durable(submitted, DispatchState.ACCEPTED)
    scheduled: list[DispatchJournalRecord] = []

    class DuplicateJournal:
        def reserve(
            self, _record: DispatchJournalRecord, *, capacity: int
        ) -> tuple[DispatchJournalRecord, bool]:
            assert capacity == 8
            return existing, False

    async def schedule(record: DispatchJournalRecord) -> None:
        scheduled.append(record)

    install_journal(value, DuplicateJournal())
    monkeypatch.setattr(value, "_schedule", schedule)
    replay = await value.submit(grant(), submitted, stream(archive()))
    assert replay.state is DispatchState.ACCEPTED
    assert scheduled == [existing]
    existing = DispatchJournalRecord(
        grant=grant(principal="other"), request=submitted, state=DispatchState.ACCEPTED
    )
    conflict = await value.submit(grant(), submitted, stream(archive()))
    assert conflict.failure is not None
    assert conflict.failure.code is DispatchFailureCode.OPERATION_CONFLICT


@pytest.mark.asyncio
async def test_submit_replays_a_durable_exact_duplicate_when_receive_slots_are_saturated(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    limiter = DispatchReceiveLimiter(1)
    assert limiter.try_acquire()
    value, _admissions = await coordinator(tmp_path, Remote(), receive_limiter=limiter)
    submitted = request(archive())
    receiving = durable(submitted, DispatchState.RECEIVING)
    value._journal.reserve(receiving, capacity=8)
    existing = DispatchJournalRecord.model_validate(
        receiving.model_dump() | {"state": DispatchState.ACCEPTED}
    )
    value._journal.replace(receiving, existing)
    scheduled: list[DispatchJournalRecord] = []

    async def schedule(record: DispatchJournalRecord) -> None:
        scheduled.append(record)

    monkeypatch.setattr(value, "_schedule", schedule)
    result = await value.submit(grant(), submitted, stream(archive()))

    assert result.state is DispatchState.ACCEPTED
    assert scheduled == [existing]
    assert limiter.try_acquire() is False
    limiter.release()


@pytest.mark.asyncio
async def test_submit_fails_full_shared_limiter_and_stops_after_receive_cancellation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    limiter = DispatchReceiveLimiter(1)
    assert limiter.try_acquire()
    value, _admissions = await coordinator(tmp_path, Remote(), receive_limiter=limiter)
    submitted = request(archive())
    limited = await value.submit(grant(), submitted, stream(archive()))
    assert limited.failure is not None
    assert limited.failure.code is DispatchFailureCode.CAPACITY_EXHAUSTED
    limiter.release()

    async def cancel_after_write(
        _request: DispatchRequest,
        _archive: AsyncIterator[bytes],
        *,
        timeout_seconds: float,
        cancel_event: asyncio.Event,
    ) -> None:
        assert timeout_seconds == value._receive_timeout
        cancel_event.set()

    monkeypatch.setattr(value._spool, "write_stream", cancel_after_write)
    second = request(
        archive(),
        operation_id="55555555-5555-4555-8555-555555555555",
        idempotency_key="66666666-6666-4666-8666-666666666666",
    )
    cancelled = await value.submit(grant(), second, stream(archive()))
    assert cancelled.state is DispatchState.CANCELLED


@pytest.mark.asyncio
async def test_cancel_wins_when_it_arrives_after_receive_before_acceptance(
    tmp_path: Path,
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())

    class OrderedGates:
        def __init__(self) -> None:
            self._inner = PrinterAdmissionGates()
            self._calls = 0
            self.post_receive_attempted = asyncio.Event()
            self.release_post_receive = asyncio.Event()

        @asynccontextmanager
        async def hold(self, printer_uuid: str) -> AsyncIterator[None]:
            self._calls += 1
            call = self._calls
            if call == 2:
                self.post_receive_attempted.set()
                await self.release_post_receive.wait()
            async with self._inner.hold(printer_uuid):
                yield
            if call == 3:
                self.release_post_receive.set()

    gates = OrderedGates()
    value._admissions = gates  # type: ignore[assignment]

    submitting = asyncio.create_task(value.submit(grant(), submitted, stream(archive())))
    await gates.post_receive_attempted.wait()
    cancelling = asyncio.create_task(
        value.cancel(grant(), submitted.operation_id, submitted.idempotency_key)
    )

    accepted, cancelled = await asyncio.gather(submitting, cancelling)

    assert accepted.state is DispatchState.CANCELLED
    assert cancelled is not None and cancelled.state is DispatchState.CANCELLED


@pytest.mark.asyncio
async def test_submit_stops_before_source_when_cancelled_after_receiving_reservation(
    tmp_path: Path,
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())

    class CancelOnExitGates:
        @asynccontextmanager
        async def hold(self, _printer_uuid: str) -> AsyncIterator[None]:
            yield
            for receiving in value._receiving.values():
                receiving.cancelled.set()

    value._admissions = CancelOnExitGates()  # type: ignore[assignment]
    result = await value.submit(grant(), submitted, stream(archive()))

    assert result.state is DispatchState.CANCELLED
    assert not (tmp_path / "state" / "spool" / f"{OPERATION_ID}.gcode.3mf").exists()


@pytest.mark.asyncio
async def test_submit_hides_storage_failure_when_a_cancelled_receipt_cannot_be_committed(
    tmp_path: Path,
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())

    class CancelOnExitGates:
        @asynccontextmanager
        async def hold(self, _printer_uuid: str) -> AsyncIterator[None]:
            yield
            next(iter(value._receiving.values())).cancelled.set()

    class FailingCancellationJournal:
        def reserve(
            self, current: DispatchJournalRecord, *, capacity: int
        ) -> tuple[DispatchJournalRecord, bool]:
            assert capacity == 8
            return current, True

        def replace(
            self, _expected: DispatchJournalRecord, _updated: DispatchJournalRecord
        ) -> DispatchJournalRecord:
            raise JournalError

    value._admissions = CancelOnExitGates()  # type: ignore[assignment]
    install_journal(value, FailingCancellationJournal())
    result = await value.submit(grant(), submitted, stream(archive()))

    assert result.failure is not None
    assert result.failure.code is DispatchFailureCode.STORAGE_UNAVAILABLE


@pytest.mark.asyncio
async def test_submit_hides_journal_failure_after_capacity_or_source_boundary(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    submitted = request(archive())
    limiter = DispatchReceiveLimiter(1)
    assert limiter.try_acquire()
    value, _admissions = await coordinator(tmp_path, Remote(), receive_limiter=limiter)

    class ReplaceFailureJournal:
        def reserve(
            self, record: DispatchJournalRecord, *, capacity: int
        ) -> tuple[DispatchJournalRecord, bool]:
            assert capacity == 8
            return record, True

        def replace(
            self, _expected: DispatchJournalRecord, _updated: DispatchJournalRecord
        ) -> DispatchJournalRecord:
            raise JournalError

    install_journal(value, ReplaceFailureJournal())
    limited = await value.submit(grant(), submitted, stream(archive()))
    assert limited.failure is not None
    assert limited.failure.code is DispatchFailureCode.STORAGE_UNAVAILABLE
    limiter.release()

    async def write_failure(*_args: object, **_kwargs: object) -> None:
        raise DispatchSpoolError

    monkeypatch.setattr(value._spool, "write_stream", write_failure)
    source_failure = await value.submit(
        grant(),
        request(
            archive(),
            operation_id="55555555-5555-4555-8555-555555555555",
            idempotency_key="66666666-6666-4666-8666-666666666666",
        ),
        stream(archive()),
    )
    assert source_failure.failure is not None
    assert source_failure.failure.code is DispatchFailureCode.STORAGE_UNAVAILABLE

    async def write_success(*_args: object, **_kwargs: object) -> None:
        return None

    monkeypatch.setattr(value._spool, "write_stream", write_success)
    accepted_failure = await value.submit(
        grant(),
        request(
            archive(),
            operation_id="77777777-7777-4777-8777-777777777777",
            idempotency_key="88888888-8888-4888-8888-888888888888",
        ),
        stream(archive()),
    )
    assert accepted_failure.failure is not None
    assert accepted_failure.failure.code is DispatchFailureCode.STORAGE_UNAVAILABLE


@pytest.mark.asyncio
async def test_cancelling_submit_records_a_source_failure_and_releases_receive_slot(
    tmp_path: Path,
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote(), receive_timeout_seconds=60)
    submitted = request(archive())
    entered = asyncio.Event()

    async def stalled() -> AsyncIterator[bytes]:
        entered.set()
        await asyncio.Event().wait()
        yield archive()

    task = asyncio.create_task(value.submit(grant(), submitted, stalled()))
    await entered.wait()
    task.cancel()
    with pytest.raises(asyncio.CancelledError):
        await task
    result = await value.result(grant(), submitted.operation_id, submitted.idempotency_key)
    assert result is not None and result.state is DispatchState.FAILED


@pytest.mark.asyncio
async def test_coordinator_helpers_bind_registry_records_and_clean_only_safe_sources(
    tmp_path: Path,
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())
    durable_record = durable(submitted, DispatchState.ACCEPTED)

    class RaisingRegistry:
        def get(self, _printer_uuid: str) -> RegisteredPrinter | None:
            raise RuntimeError

    value._registry = RaisingRegistry()
    assert value._current_profile(submitted)[1] is DispatchFailureCode.PRINTER_UNAVAILABLE
    value._registry = Registry()
    stale = submitted.model_copy(update={"slicer_profile_id": "different-profile"})
    assert value._current_profile(stale)[1] is DispatchFailureCode.PROFILE_STALE
    disabled = Registry()
    disabled.record = disabled.record.model_copy(update={"dispatch_enabled": False})
    value._registry = disabled
    assert value._current_profile(submitted)[1] is DispatchFailureCode.DISPATCH_DISABLED

    value._registry = Registry()
    install_journal(value, InMemoryJournal(None))
    assert value._current_record(durable_record) is None
    install_journal(
        value,
        InMemoryJournal(
            DispatchJournalRecord(
                grant=grant(principal="other"), request=submitted, state=DispatchState.ACCEPTED
            )
        ),
    )
    assert value._current_record(durable_record) is None
    install_journal(value, InMemoryJournal(durable_record))
    assert value._current_record(durable_record) == durable_record
    candidate, qualification = value._qualify(
        durable_record,
        safety_profile(),
        b"not a valid archive",
    )
    assert candidate is None and qualification is None

    class RemovingSpool:
        def __init__(self) -> None:
            self.calls = 0

        def remove(self, _request: DispatchRequest) -> None:
            self.calls += 1
            raise DispatchSpoolError

    removing = RemovingSpool()
    value._spool = removing  # type: ignore[assignment]
    value._remove_after_terminal(durable_record)
    assert removing.calls == 0
    failed = DispatchJournalRecord(
        grant=grant(),
        request=submitted,
        state=DispatchState.FAILED,
        failure=DispatchFailure(code=DispatchFailureCode.SOURCE_INVALID),
    )
    value._remove_after_terminal(failed)
    assert removing.calls == 1
    receiving = value._receiving.setdefault(
        (submitted.operation_id, submitted.idempotency_key), _ReceivingOperation()
    )
    value._finish_receiving(submitted, receiving)
    assert (submitted.operation_id, submitted.idempotency_key) not in value._receiving
    assert receiving.done.is_set()
    value._finish_receiving(submitted, receiving)


@pytest.mark.asyncio
async def test_qualification_bounds_its_authority_and_rejects_a_denied_assessment(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())
    maximum_principal = "a" * 255
    accepted = DispatchJournalRecord(
        grant=grant(principal=maximum_principal),
        request=submitted,
        state=DispatchState.ACCEPTED,
    )

    candidate, qualification = value._qualify(accepted, safety_profile(), archive())

    assert candidate is not None and qualification is not None
    assert qualification.authority_id == maximum_principal

    denied = type(
        "DeniedAssessment",
        (),
        {"state": ArtifactOperationState.DENIED, "qualification": None},
    )()
    monkeypatch.setattr(
        "klove.orchestration.dispatch.assess_artifact_intent", lambda *_args, **_kwargs: denied
    )
    rejected_candidate, rejected_qualification = value._qualify(
        accepted, safety_profile(), archive()
    )

    assert rejected_candidate is None and rejected_qualification is None

    install_journal(value, InMemoryJournal(accepted))
    no_confirmation = StartOperationResult(
        operation_id=submitted.operation_id,
        idempotency_key=submitted.idempotency_key,
        state=StartState.DENIED,
        failure=StartFailure(
            boundary=StartBoundary.INTERNAL, code=StartFailureCode.INTERNAL_FAILURE
        ),
    )
    final = value._finalize_start(accepted, no_confirmation)
    assert final.state is DispatchState.OUTCOME_UNKNOWN
    assert final.failure is not None
    assert final.failure.code is DispatchFailureCode.START_AMBIGUOUS


@pytest.mark.asyncio
async def test_qualification_stage_stops_on_each_fail_closed_pre_upload_boundary(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())
    accepted = durable(submitted, DispatchState.ACCEPTED)
    terminal_codes: list[DispatchFailureCode] = []

    def terminal(
        record: DispatchJournalRecord, _state: DispatchState, code: DispatchFailureCode
    ) -> DispatchJournalRecord:
        terminal_codes.append(code)
        return record

    monkeypatch.setattr(value, "_terminal", terminal)
    monkeypatch.setattr(value, "_current_record", lambda _record: None)
    assert await value._qualify_and_upload(accepted) is accepted
    monkeypatch.setattr(value, "_current_record", lambda _record: accepted)
    monkeypatch.setattr(
        value, "_current_profile", lambda _request: (None, DispatchFailureCode.PROFILE_STALE)
    )
    assert await value._qualify_and_upload(accepted) is accepted

    class MissingSpool:
        def read(self, _request: DispatchRequest) -> bytes:
            raise DispatchSpoolError

    value._spool = MissingSpool()  # type: ignore[assignment]
    monkeypatch.setattr(
        value,
        "_current_profile",
        lambda _request: (safety_profile(), DispatchFailureCode.INTERNAL_FAILURE),
    )
    assert await value._qualify_and_upload(accepted) is accepted
    monkeypatch.setattr(value._spool, "read", lambda _request: archive())
    monkeypatch.setattr(value, "_qualify", lambda *_args: (None, None))
    assert await value._qualify_and_upload(accepted) is accepted

    assert terminal_codes == [
        DispatchFailureCode.PROFILE_STALE,
        DispatchFailureCode.SOURCE_MISSING,
        DispatchFailureCode.QUALIFICATION_DENIED,
    ]


@pytest.mark.asyncio
async def test_qualification_stage_preserves_ambiguous_or_denied_upload_outcomes(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())
    accepted = durable(submitted, DispatchState.ACCEPTED)
    codes: list[DispatchFailureCode] = []

    class ReadableSpool:
        def read(self, _request: DispatchRequest) -> bytes:
            return archive()

    class Uploader:
        def __init__(self, state: UploadState) -> None:
            self.state = state

        async def execute(self, *_args: object, **_kwargs: object) -> object:
            return type("UploadResult", (), {"state": self.state, "verified": None})()

    def changed(
        record: DispatchJournalRecord, *, state: DispatchState, **_kwargs: object
    ) -> DispatchJournalRecord:
        return record.model_copy(update={"state": state})

    def terminal(
        record: DispatchJournalRecord, _state: DispatchState, code: DispatchFailureCode
    ) -> DispatchJournalRecord:
        codes.append(code)
        return record

    value._spool = ReadableSpool()  # type: ignore[assignment]
    monkeypatch.setattr(value, "_current_record", lambda _record: accepted)
    monkeypatch.setattr(
        value,
        "_current_profile",
        lambda _request: (safety_profile(), DispatchFailureCode.INTERNAL_FAILURE),
    )
    monkeypatch.setattr(value, "_qualify", lambda *_args: (object(), object()))
    monkeypatch.setattr("klove.orchestration.dispatch._changed", changed)
    monkeypatch.setattr(value, "_terminal", terminal)
    for state in (UploadState.OUTCOME_UNKNOWN, UploadState.DENIED):
        install_journal(value, InMemoryJournal(accepted))
        value._uploader = Uploader(state)  # type: ignore[assignment]
        assert (await value._qualify_and_upload(accepted)).state is DispatchState.UPLOADING

    assert codes == [DispatchFailureCode.UPLOAD_AMBIGUOUS, DispatchFailureCode.UPLOAD_DENIED]


@pytest.mark.asyncio
async def test_recovery_marks_receiving_uploading_and_lost_source_records_safely(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())
    receiving = durable(submitted, DispatchState.RECEIVING)
    accepted = durable(submitted, DispatchState.ACCEPTED)
    uploading = accepted.model_copy(update={"state": DispatchState.UPLOADING})
    events: list[DispatchFailureCode] = []

    class RecoverySpool:
        def discard_incomplete(self, _request: DispatchRequest) -> None:
            return None

        def exists(self, _request: DispatchRequest) -> bool:
            return False

    def terminal(
        record: DispatchJournalRecord, _state: DispatchState, code: DispatchFailureCode
    ) -> DispatchJournalRecord:
        events.append(code)
        return record

    value._spool = RecoverySpool()  # type: ignore[assignment]
    monkeypatch.setattr(value, "_terminal", terminal)

    assert value._recover_record(receiving) is receiving
    assert value._recover_record(uploading) is uploading
    assert value._recover_record(accepted) is accepted
    assert events == [
        DispatchFailureCode.SOURCE_INVALID,
        DispatchFailureCode.UPLOAD_AMBIGUOUS,
        DispatchFailureCode.SOURCE_MISSING,
    ]
    value._spool = type(
        "PresentRecoverySpool",
        (),
        {"exists": staticmethod(lambda _request: True)},
    )()
    assert value._recover_record(accepted) is accepted


@pytest.mark.asyncio
async def test_start_and_reconciliation_stages_deny_every_incomplete_evidence_boundary(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())
    terminals: list[DispatchFailureCode] = []

    def synthetic(
        state: DispatchState, *, verified: object | None = None, start: object | None = None
    ) -> DispatchJournalRecord:
        return DispatchJournalRecord.model_construct(
            grant=grant(),
            request=submitted,
            state=state,
            qualification=None,
            verified=verified,
            start=start,
            failure=None,
        )

    def terminal(
        record: DispatchJournalRecord, _state: DispatchState, code: DispatchFailureCode
    ) -> DispatchJournalRecord:
        terminals.append(code)
        return record

    monkeypatch.setattr(value, "_terminal", terminal)
    monkeypatch.setattr(value, "_current_record", lambda _record: None)
    verified_record = synthetic(DispatchState.STARTING, verified=object())
    assert await value._start(verified_record) is verified_record

    monkeypatch.setattr(value, "_current_record", lambda _record: verified_record)
    monkeypatch.setattr(
        value, "_current_profile", lambda _request: (None, DispatchFailureCode.PROFILE_STALE)
    )
    assert await value._start(verified_record) is verified_record
    no_verified = synthetic(DispatchState.STARTING)
    monkeypatch.setattr(value, "_current_record", lambda _record: no_verified)
    monkeypatch.setattr(
        value,
        "_current_profile",
        lambda _request: (safety_profile(), DispatchFailureCode.INTERNAL_FAILURE),
    )
    assert await value._start(no_verified) is no_verified
    mismatch = synthetic(
        DispatchState.STARTING,
        verified=type(
            "Verified", (), {"qualification": type("Qualification", (), {"target": object()})()}
        )(),
    )
    monkeypatch.setattr(value, "_current_record", lambda _record: mismatch)
    assert await value._start(mismatch) is mismatch

    started = synthetic(DispatchState.STARTING, verified=verified_upload())
    monkeypatch.setattr(value, "_current_record", lambda _record: started)

    class StartResult:
        confirmation = None

        def __init__(self, state: StartState) -> None:
            self.state = state

    class Starter:
        def __init__(self, state: StartState) -> None:
            self.state = state

        async def execute(self, _verified: object, *, admission_lease: object) -> StartResult:
            return StartResult(self.state)

    for state in (StartState.OUTCOME_UNKNOWN, StartState.DENIED, StartState.CONFIRMED):
        value._starter = Starter(state)  # type: ignore[assignment]
        assert await value._start(started) is started

    monkeypatch.setattr(value, "_current_record", lambda _record: None)
    assert await value._reconcile_started(started) is started
    monkeypatch.setattr(value, "_current_record", lambda _record: started)
    assert await value._reconcile_printing(started) is started
    unknown_result = type("StartResult", (), {"confirmation": None})()
    assert await value._finalize_observed_start(started, unknown_result, object()) is started  # type: ignore[arg-type]

    assert terminals == [
        DispatchFailureCode.PROFILE_STALE,
        DispatchFailureCode.PROFILE_STALE,
        DispatchFailureCode.PROFILE_STALE,
        DispatchFailureCode.START_AMBIGUOUS,
        DispatchFailureCode.START_DENIED,
        DispatchFailureCode.START_AMBIGUOUS,
        DispatchFailureCode.START_AMBIGUOUS,
    ]


@pytest.mark.asyncio
async def test_fresh_start_observation_must_match_the_confirmed_job(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())
    verified = verified_upload()
    record = DispatchJournalRecord.model_construct(
        grant=grant(),
        request=submitted,
        state=DispatchState.STARTING,
        qualification=verified.qualification,
        verified=verified,
        start=None,
        failure=None,
    )
    confirmation = StartOperationResult(
        operation_id=submitted.operation_id,
        idempotency_key=submitted.idempotency_key,
        state=StartState.CONFIRMED,
        confirmation=StartConfirmation(
            path=verified.path,
            eventtime=1,
            phase=PrinterPhase.PRINTING,
            file_position=1,
            job=history_job(filename=verified.path),
        ),
    )
    terminals: list[DispatchFailureCode] = []

    class NoCurrentObservation:
        def __init__(self) -> None:
            self.calls = 0

        async def observe(self, *_args: object, **_kwargs: object) -> StartObservation | None:
            self.calls += 1
            if self.calls == 1:
                return None
            return StartObservation(
                eventtime=1,
                phase=PrinterPhase.IDLE,
                filename="",
                file_position=0,
                latest_job=None,
            )

    def terminal(
        current: DispatchJournalRecord, _state: DispatchState, code: DispatchFailureCode
    ) -> DispatchJournalRecord:
        terminals.append(code)
        return current

    value._starter = NoCurrentObservation()  # type: ignore[assignment]
    monkeypatch.setattr(value, "_terminal", terminal)
    returned = await value._finalize_observed_start(record, confirmation, object())  # type: ignore[arg-type]
    missing_job = await value._finalize_observed_start(record, confirmation, object())  # type: ignore[arg-type]

    assert returned is record
    assert missing_job is record
    assert terminals == [DispatchFailureCode.START_AMBIGUOUS, DispatchFailureCode.START_AMBIGUOUS]


@pytest.mark.asyncio
async def test_task_bookkeeping_and_run_fail_closed_on_missing_or_unexpected_state(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    value, _admissions = await coordinator(tmp_path, Remote())
    submitted = request(archive())
    accepted = durable(submitted, DispatchState.ACCEPTED)
    blocker = asyncio.Event()

    async def blocked() -> None:
        await blocker.wait()

    running = asyncio.create_task(blocked())
    value._tasks[submitted.operation_id] = running
    await value._schedule(accepted)
    assert value._tasks[submitted.operation_id] is running
    value._forget_task(submitted.operation_id, asyncio.create_task(asyncio.sleep(0)))
    assert value._tasks[submitted.operation_id] is running
    running.cancel()
    with pytest.raises(asyncio.CancelledError):
        await running

    install_journal(value, InMemoryJournal(None))
    await value._run(submitted.operation_id, submitted.idempotency_key)

    install_journal(value, InMemoryJournal(None, failure=True))
    await value._run(submitted.operation_id, submitted.idempotency_key)
    install_journal(value, InMemoryJournal(accepted))
    monkeypatch.setattr(
        value, "_qualify_and_upload", lambda _record: (_ for _ in ()).throw(RuntimeError)
    )
    terminals: list[DispatchFailureCode] = []

    def terminal(
        _record: DispatchJournalRecord, _state: DispatchState, code: DispatchFailureCode
    ) -> DispatchJournalRecord:
        terminals.append(code)
        return accepted

    monkeypatch.setattr(value, "_terminal", terminal)
    await value._run(submitted.operation_id, submitted.idempotency_key)

    class SequenceJournal:
        def __init__(self, final: DispatchJournalRecord | None) -> None:
            self.calls = 0
            self.final = final

        def lookup(self, _operation_id: str, _idempotency_key: str) -> DispatchJournalRecord | None:
            self.calls += 1
            return accepted if self.calls == 1 else self.final

    for state, _expected in (
        (DispatchState.UPLOADING, DispatchFailureCode.UPLOAD_AMBIGUOUS),
        (DispatchState.STARTING, DispatchFailureCode.START_AMBIGUOUS),
        (DispatchState.FAILED, DispatchFailureCode.SOURCE_INVALID),
    ):
        final = (
            DispatchJournalRecord(
                grant=grant(),
                request=submitted,
                state=state,
                failure=DispatchFailure(code=DispatchFailureCode.SOURCE_INVALID),
            )
            if state is DispatchState.FAILED
            else accepted.model_copy(update={"state": state})
        )
        install_journal(value, SequenceJournal(final))
        await value._run(submitted.operation_id, submitted.idempotency_key)

    install_journal(value, SequenceJournal(None))
    await value._run(submitted.operation_id, submitted.idempotency_key)

    class ErrorAfterFailureJournal:
        calls = 0

        def lookup(self, _operation_id: str, _idempotency_key: str) -> DispatchJournalRecord:
            self.calls += 1
            if self.calls == 1:
                return accepted
            raise JournalError

    install_journal(value, ErrorAfterFailureJournal())
    await value._run(submitted.operation_id, submitted.idempotency_key)

    assert terminals == [
        DispatchFailureCode.INTERNAL_FAILURE,
        DispatchFailureCode.UPLOAD_AMBIGUOUS,
        DispatchFailureCode.START_AMBIGUOUS,
    ]


@pytest.mark.asyncio
async def test_coordinator_qualifies_uploads_and_starts_one_exact_registry_target(
    tmp_path: Path,
) -> None:
    remote = Remote()
    value, _admissions = await coordinator(tmp_path, remote)
    submitted = request(archive())

    accepted = await value.submit(grant(), submitted, stream(archive()))
    duplicate = await value.submit(grant(), submitted, stream(archive()))
    await eventually(value, submitted, expected=DispatchState.PRINTING)
    result = await value.result(grant(), submitted.operation_id, submitted.idempotency_key)

    assert accepted.state is DispatchState.ACCEPTED
    assert duplicate.operation_id == submitted.operation_id
    assert result is not None and result.remote_path == f"klove/{OPERATION_ID}.gcode"
    assert remote.uploads == [f"klove/{OPERATION_ID}.gcode"]
    assert remote.dispatches == [f"klove/{OPERATION_ID}.gcode"]
    assert not (tmp_path / "state" / "spool" / f"{OPERATION_ID}.gcode.3mf").exists()


@pytest.mark.asyncio
async def test_coordinator_rejects_substitution_and_cancels_before_upload(tmp_path: Path) -> None:
    remote = Remote()
    value, _admissions = await coordinator(tmp_path, remote)
    submitted = request(archive())

    accepted = await value.submit(grant(), submitted, stream(archive()))
    conflict = await value.submit(grant(principal="other-worker"), submitted, stream(archive()))
    cancelled = await value.cancel(grant(), submitted.operation_id, submitted.idempotency_key)
    await asyncio.sleep(0)

    assert accepted.state is DispatchState.ACCEPTED
    assert conflict.failure is not None
    assert conflict.failure.code is DispatchFailureCode.OPERATION_CONFLICT
    assert cancelled is not None and cancelled.state is DispatchState.CANCELLED
    assert remote.uploads == []
    assert remote.dispatches == []


@pytest.mark.asyncio
async def test_coordinator_fences_lost_upload_response_and_retains_source(tmp_path: Path) -> None:
    remote = Remote()
    remote.fail_upload = True
    value, _admissions = await coordinator(tmp_path, remote)
    submitted = request(archive())

    await value.submit(grant(), submitted, stream(archive()))
    await asyncio.sleep(0.2)
    await eventually(value, submitted, expected=DispatchState.OUTCOME_UNKNOWN)
    result = await value.result(grant(), submitted.operation_id, submitted.idempotency_key)

    assert result is not None and result.failure is not None
    assert result.failure.code is DispatchFailureCode.UPLOAD_AMBIGUOUS
    assert remote.dispatches == []
    assert (tmp_path / "state" / "spool" / f"{OPERATION_ID}.gcode.3mf").exists()


@pytest.mark.asyncio
async def test_coordinator_cancellation_does_not_release_admission_before_upload_child_finishes(
    tmp_path: Path,
) -> None:
    remote = Remote()
    remote.release_upload.clear()
    value, admissions = await coordinator(tmp_path, remote)
    submitted = request(archive())

    await value.submit(grant(), submitted, stream(archive()))
    await remote.upload_entered.wait()
    task = value._tasks[submitted.operation_id]
    task.cancel()
    with pytest.raises(asyncio.CancelledError):
        await task
    entered = asyncio.Event()

    async def lifecycle_like_contender() -> None:
        async with admissions.hold(PRINTER_UUID):
            entered.set()

    contender = asyncio.create_task(lifecycle_like_contender())
    await asyncio.sleep(0)
    assert not entered.is_set()
    remote.release_upload.set()
    await contender
    assert entered.is_set()


@pytest.mark.asyncio
async def test_coordinator_reconciles_exact_printing_job_to_its_terminal_history_state(
    tmp_path: Path,
) -> None:
    remote = Remote()
    value, _admissions = await coordinator(tmp_path, remote)
    submitted = request(archive())

    await value.submit(grant(), submitted, stream(archive()))
    await eventually(value, submitted, expected=DispatchState.PRINTING)
    remote.status = JobHistoryStatus.COMPLETED
    reconciled = await value.result(grant(), submitted.operation_id, submitted.idempotency_key)

    assert reconciled is not None and reconciled.state is DispatchState.COMPLETED


@pytest.mark.asyncio
async def test_coordinator_resolves_post_start_unknown_only_from_later_exact_evidence(
    tmp_path: Path,
) -> None:
    remote = Remote()
    remote.fail_queries = True
    value, _admissions = await coordinator(tmp_path, remote)
    submitted = request(archive())

    await value.submit(grant(), submitted, stream(archive()))
    await asyncio.sleep(0.2)
    await eventually(value, submitted, expected=DispatchState.OUTCOME_UNKNOWN)
    remote.fail_queries = False
    remote.status = JobHistoryStatus.COMPLETED
    reconciled = await value.result(grant(), submitted.operation_id, submitted.idempotency_key)

    assert reconciled is not None and reconciled.state is DispatchState.COMPLETED


@pytest.mark.asyncio
async def test_restart_reconciles_post_confirmation_ambiguity_without_a_deleted_source(
    tmp_path: Path,
) -> None:
    remote = Remote()
    value, _admissions = await coordinator(tmp_path, remote)
    submitted = request(archive())

    await value.submit(grant(), submitted, stream(archive()))
    await eventually(value, submitted, expected=DispatchState.PRINTING)
    remote.fail_queries = True
    unknown = await value.result(grant(), submitted.operation_id, submitted.idempotency_key)

    assert unknown is not None and unknown.state is DispatchState.OUTCOME_UNKNOWN
    assert not (tmp_path / "state" / "spool" / f"{OPERATION_ID}.gcode.3mf").exists()

    await value.initialize()

    assert bool(value._ready)


@pytest.mark.asyncio
async def test_concurrent_result_polls_do_not_regress_a_terminal_print_to_unknown(
    tmp_path: Path,
) -> None:
    remote = Remote()
    value, _admissions = await coordinator(tmp_path, remote)
    submitted = request(archive())

    await value.submit(grant(), submitted, stream(archive()))
    await eventually(value, submitted, expected=DispatchState.PRINTING)
    remote.query_entered.clear()
    remote.release_query.clear()
    remote.fail_after_query = remote.query_count + 1
    first = asyncio.create_task(
        value.result(grant(), submitted.operation_id, submitted.idempotency_key)
    )
    await remote.query_entered.wait()
    second = asyncio.create_task(
        value.result(grant(), submitted.operation_id, submitted.idempotency_key)
    )
    remote.status = JobHistoryStatus.COMPLETED
    remote.release_query.set()

    first_result, second_result = await asyncio.gather(first, second)

    assert first_result is not None and first_result.state is DispatchState.COMPLETED
    assert second_result is not None and second_result.state is DispatchState.COMPLETED


@pytest.mark.asyncio
async def test_starting_without_a_start_journal_row_resumes_only_during_initialize_recovery(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    remote = Remote()
    value, _admissions = await coordinator(tmp_path, remote)
    submitted = request(archive())
    await value.submit(grant(), submitted, stream(archive()))
    await eventually(value, submitted, expected=DispatchState.PRINTING)
    confirmed = value._journal.lookup(submitted.operation_id, submitted.idempotency_key)
    assert confirmed is not None
    crashed = confirmed.model_copy(update={"state": DispatchState.STARTING, "start": None})
    journal = InMemoryJournal(crashed)
    install_journal(value, journal)
    reconciled = StartOperationResult(
        operation_id=submitted.operation_id,
        idempotency_key=submitted.idempotency_key,
        state=StartState.DENIED,
        failure=StartFailure(
            boundary=StartBoundary.RECONCILIATION,
            code=StartFailureCode.RECONCILIATION_PENDING,
        ),
    )

    class MissingStartRow:
        execute_calls = 0

        async def reconcile(self, *_args: object, **_kwargs: object) -> StartOperationResult:
            return reconciled

        async def execute(self, *_args: object, **_kwargs: object) -> StartOperationResult:
            self.execute_calls += 1
            return reconciled

    starter = MissingStartRow()
    value._starter = starter  # type: ignore[assignment]
    polled = await value._reconcile_started(crashed)
    scheduled: list[DispatchJournalRecord] = []

    async def schedule(record: DispatchJournalRecord) -> None:
        scheduled.append(record)

    monkeypatch.setattr(value, "_schedule", schedule)
    value._spool.write(submitted, archive())
    await value.initialize()

    assert polled.state is DispatchState.STARTING
    assert journal.current is not None and journal.current.state is DispatchState.VERIFIED
    assert scheduled == [journal.current]
    assert starter.execute_calls == 0

    journal.current = crashed
    monkeypatch.setattr(
        value,
        "_current_profile",
        lambda _request: (None, DispatchFailureCode.PRINTER_UNAVAILABLE),
    )
    unavailable = await value._reconcile_started(crashed, resume_missing_start=True)
    assert unavailable.failure is not None
    assert unavailable.failure.code is DispatchFailureCode.PRINTER_UNAVAILABLE

    journal.current = crashed
    monkeypatch.setattr(
        value,
        "_current_profile",
        lambda _request: (safety_profile(generation=8), DispatchFailureCode.INTERNAL_FAILURE),
    )
    stale = await value._reconcile_started(crashed, resume_missing_start=True)
    assert stale.failure is not None
    assert stale.failure.code is DispatchFailureCode.PROFILE_STALE


@pytest.mark.asyncio
async def test_cancelling_a_stalled_receive_stops_source_before_the_receive_timeout(
    tmp_path: Path,
) -> None:
    remote = Remote()
    value, _admissions = await coordinator(tmp_path, remote, receive_timeout_seconds=60)
    submitted = request(archive())
    entered = asyncio.Event()

    async def stalled_source() -> AsyncIterator[bytes]:
        entered.set()
        await asyncio.Event().wait()
        yield archive()

    submit_task = asyncio.create_task(value.submit(grant(), submitted, stalled_source()))
    await entered.wait()
    cancelled = await asyncio.wait_for(
        value.cancel(grant(), submitted.operation_id, submitted.idempotency_key), timeout=0.5
    )
    submitted_result = await asyncio.wait_for(submit_task, timeout=0.5)

    assert cancelled is not None and cancelled.state is DispatchState.CANCELLED
    assert submitted_result.state is DispatchState.CANCELLED
    assert remote.uploads == []
    assert remote.dispatches == []


@pytest.mark.asyncio
async def test_coordinator_stream_timeout_records_source_failure_after_reservation(
    tmp_path: Path,
) -> None:
    remote = Remote()
    value, _admissions = await coordinator(
        tmp_path,
        remote,
        receive_timeout_seconds=1,
        receive_limiter=DispatchReceiveLimiter(1),
    )
    value._receive_timeout = 0.01
    submitted = request(archive())

    async def too_slow() -> AsyncIterator[bytes]:
        await asyncio.sleep(0.1)
        yield archive()

    result = await value.submit(grant(), submitted, too_slow())

    assert result.state is DispatchState.FAILED
    assert result.failure is not None
    assert result.failure.code is DispatchFailureCode.SOURCE_INVALID
