from __future__ import annotations

import hashlib
import stat
import struct
from io import BytesIO
from pathlib import Path
from typing import cast
from zipfile import ZIP_BZIP2, ZIP_DEFLATED, ZipFile, ZipInfo

import pytest

import klove.domain.artifact_validation as validation
from klove.domain.artifacts import (
    ArtifactBoundary,
    ArtifactFailure,
    ArtifactFailureCode,
    ArtifactIntent,
    ArtifactLimits,
)

FIXTURES = Path(__file__).parents[1] / "fixtures" / "artifacts"
SELECTED_PATH = "Metadata/plate_1.gcode"
VALID_GCODE = b"; generated by OrcaSlicer 2.3.0\nG28\nG1 X1.0 Y2.0\n"
CORE_ENTRIES = (
    ("[Content_Types].xml", b"<Types/>"),
    ("_rels/.rels", b"<Relationships/>"),
    ("3D/3dmodel.model", b"<model/>"),
)


def base_intent() -> ArtifactIntent:
    return ArtifactIntent.model_validate_json(
        (FIXTURES / "accepted-intent.json").read_text(encoding="utf-8")
    )


def zip_bytes(
    entries: list[tuple[str | ZipInfo, bytes]] | None = None,
    *,
    compression: int = ZIP_DEFLATED,
    archive_comment: bytes = b"",
) -> bytes:
    members: list[tuple[str | ZipInfo, bytes]] = list(CORE_ENTRIES)
    members.append((SELECTED_PATH, VALID_GCODE))
    if entries is not None:
        members = entries
    target = BytesIO()
    with ZipFile(target, mode="w", compression=compression, allowZip64=True) as bundle:
        for name, content in members:
            bundle.writestr(name, content)
        bundle.comment = archive_comment
    return target.getvalue()


def intent_for(payload: bytes, *, archive_path: str = SELECTED_PATH) -> ArtifactIntent:
    request = base_intent()
    return request.model_copy(
        update={
            "artifact": request.artifact.model_copy(
                update={
                    "archive_sha256": "sha256:" + hashlib.sha256(payload).hexdigest(),
                    "compressed_size_bytes": len(payload),
                }
            ),
            "selected_plate": request.selected_plate.model_copy(
                update={"archive_path": archive_path}
            ),
        }
    )


def inspect(payload: bytes, *, limits: ArtifactLimits | None = None) -> object:
    return validation.inspect_gcode_3mf(
        intent_for(payload),
        payload,
        limits=limits or ArtifactLimits(),
    )


def assert_failure(
    result: object,
    boundary: ArtifactBoundary,
    code: ArtifactFailureCode,
) -> None:
    assert result == ArtifactFailure(boundary=boundary, code=code)


def central_record_offset(payload: bytes, name: str) -> int:
    eocd = len(payload) - 22
    directory_offset = cast(int, struct.unpack_from("<L", payload, eocd + 16)[0])
    offset = directory_offset
    while payload[offset : offset + 4] == b"PK\x01\x02":
        name_size, extra_size, comment_size = struct.unpack_from("<3H", payload, offset + 28)
        current = payload[offset + 46 : offset + 46 + name_size].decode("utf-8")
        if current == name:
            return offset
        offset += 46 + name_size + extra_size + comment_size
    raise AssertionError(name)


def patch_u16(payload: bytes, offset: int, value: int) -> bytes:
    changed = bytearray(payload)
    struct.pack_into("<H", changed, offset, value)
    return bytes(changed)


def patch_u32(payload: bytes, offset: int, value: int) -> bytes:
    changed = bytearray(payload)
    struct.pack_into("<L", changed, offset, value)
    return bytes(changed)


def as_zip64(payload: bytes) -> bytes:
    eocd_offset = len(payload) - 22
    eocd = bytearray(payload[eocd_offset:])
    entries = struct.unpack_from("<H", eocd, 10)[0]
    directory_size = struct.unpack_from("<L", eocd, 12)[0]
    directory_offset = struct.unpack_from("<L", eocd, 16)[0]
    record = struct.pack(
        "<4sQ2H2L4Q",
        b"PK\x06\x06",
        44,
        45,
        45,
        0,
        0,
        entries,
        entries,
        directory_size,
        directory_offset,
    )
    locator = struct.pack("<4sLQL", b"PK\x06\x07", 0, eocd_offset, 1)
    struct.pack_into("<4H2L", eocd, 4, 0, 0, 0xFFFF, 0xFFFF, 0xFFFFFFFF, 0xFFFFFFFF)
    return payload[:eocd_offset] + record + locator + bytes(eocd)


@pytest.mark.parametrize(
    "name",
    [
        "../escape.gcode",
        "/absolute.gcode",
        "Metadata\\plate.gcode",
        "C:/Metadata/plate.gcode",
        "Metadata//plate.gcode",
        "Metadata/./plate.gcode",
        "Metadata/../plate.gcode",
        "Metadata/ plate.gcode",
        "Metadata/tab\tplate.gcode",
        "Metadata/pl\u00e1te.gcode",
    ],
)
def test_unsafe_member_names_are_denied(name: str) -> None:
    payload = zip_bytes([*CORE_ENTRIES, (name, b"unselected"), (SELECTED_PATH, VALID_GCODE)])

    assert_failure(
        inspect(payload),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSAFE_ARCHIVE,
    )


def test_nul_sanitized_duplicate_and_case_alias_names_are_denied() -> None:
    payload = zip_bytes()
    central = central_record_offset(payload, SELECTED_PATH)
    with ZipFile(BytesIO(payload)) as bundle:
        local = next(
            info.header_offset for info in bundle.infolist() if info.filename == SELECTED_PATH
        )
    nul_payload = bytearray(payload)
    nul_index = len("Metadata/plate_1")
    nul_payload[central + 46 + nul_index] = 0
    nul_payload[local + 30 + nul_index] = 0
    assert_failure(
        inspect(bytes(nul_payload)),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSAFE_ARCHIVE,
    )

    with pytest.warns(UserWarning, match="Duplicate name"):
        duplicate = zip_bytes(
            [*CORE_ENTRIES, (SELECTED_PATH, VALID_GCODE), (SELECTED_PATH, VALID_GCODE)]
        )
    assert_failure(
        inspect(duplicate),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSAFE_ARCHIVE,
    )
    case_alias = zip_bytes(
        [
            *CORE_ENTRIES,
            ("Metadata/readme.txt", b"a"),
            ("metadata/README.TXT", b"b"),
            (SELECTED_PATH, VALID_GCODE),
        ]
    )
    assert_failure(
        inspect(case_alias),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSAFE_ARCHIVE,
    )


def test_links_encryption_and_unsupported_zip_features_are_denied() -> None:
    link = ZipInfo("Metadata/link")
    link.create_system = 3
    link.external_attr = (stat.S_IFLNK | 0o777) << 16
    linked = zip_bytes([*CORE_ENTRIES, (link, b"target"), (SELECTED_PATH, VALID_GCODE)])
    assert_failure(inspect(linked), ArtifactBoundary.ARCHIVE, ArtifactFailureCode.UNSAFE_ARCHIVE)

    payload = zip_bytes()
    central = central_record_offset(payload, SELECTED_PATH)
    with ZipFile(BytesIO(payload)) as bundle:
        local = next(
            info.header_offset for info in bundle.infolist() if info.filename == SELECTED_PATH
        )
    encrypted = patch_u16(payload, central + 8, 1)
    encrypted = patch_u16(encrypted, local + 6, 1)
    assert_failure(inspect(encrypted), ArtifactBoundary.ARCHIVE, ArtifactFailureCode.UNSAFE_ARCHIVE)

    unsupported = zip_bytes(compression=ZIP_BZIP2)
    assert_failure(
        inspect(unsupported),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSUPPORTED_ARCHIVE,
    )

    unsupported_flags = patch_u16(payload, central + 8, 1 << 4)
    assert_failure(
        inspect(unsupported_flags),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSUPPORTED_ARCHIVE,
    )

    commented = ZipInfo("Metadata/commented")
    commented.comment = b"comment"
    with_comment = zip_bytes([*CORE_ENTRIES, (commented, b"content"), (SELECTED_PATH, VALID_GCODE)])
    assert_failure(
        inspect(with_comment),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSUPPORTED_ARCHIVE,
    )

    volume = patch_u16(payload, central + 34, 1)
    assert_failure(
        inspect(volume),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSUPPORTED_ARCHIVE,
    )


def test_missing_3mf_parts_or_exact_selected_plate_are_denied_without_inference() -> None:
    not_3mf = zip_bytes([(SELECTED_PATH, VALID_GCODE)])
    assert_failure(
        inspect(not_3mf),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSUPPORTED_ARCHIVE,
    )
    geometry_only = zip_bytes(list(CORE_ENTRIES))
    assert_failure(
        inspect(geometry_only),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.EVIDENCE_MISSING,
    )
    other_plate = zip_bytes([*CORE_ENTRIES, ("Metadata/plate_2.gcode", VALID_GCODE)])
    assert_failure(
        inspect(other_plate),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.EVIDENCE_MISSING,
    )


def test_entry_count_expanded_size_ratio_and_selected_size_limits_are_enforced() -> None:
    payload = zip_bytes()
    assert_failure(
        inspect(payload, limits=ArtifactLimits(max_zip_entries=1)),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )

    central = central_record_offset(payload, SELECTED_PATH)
    zero_compressed_size = patch_u32(payload, central + 20, 0)
    assert_failure(
        inspect(zero_compressed_size),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )
    assert_failure(
        inspect(
            payload,
            limits=ArtifactLimits(
                max_archive_expanded_bytes=64,
                max_gcode_bytes=64,
                max_gcode_header_bytes=64,
                max_gcode_line_bytes=64,
            ),
        ),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )
    bomb = zip_bytes(
        [*CORE_ENTRIES, ("Metadata/padding", b"A" * 4096), (SELECTED_PATH, VALID_GCODE)]
    )
    assert_failure(
        inspect(bomb, limits=ArtifactLimits(max_compression_ratio=2)),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )
    large_gcode_payload = zip_bytes(
        [*CORE_ENTRIES, (SELECTED_PATH, VALID_GCODE + b"; filler\n" * 10)]
    )
    assert_failure(
        inspect(
            large_gcode_payload,
            limits=ArtifactLimits(
                max_gcode_bytes=64,
                max_gcode_header_bytes=64,
                max_gcode_line_bytes=32,
            ),
        ),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )


def test_empty_archive_empty_selected_member_and_declared_entry_mismatch_are_denied() -> None:
    empty_archive = zip_bytes([])
    assert_failure(inspect(empty_archive), ArtifactBoundary.ARCHIVE, ArtifactFailureCode.MALFORMED)

    empty_selected = zip_bytes([*CORE_ENTRIES, (SELECTED_PATH, b"")])
    assert_failure(
        inspect(empty_selected),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.INVALID_GCODE,
    )

    payload = zip_bytes()
    eocd = len(payload) - 22
    mismatched_count = patch_u16(payload, eocd + 8, 1)
    mismatched_count = patch_u16(mismatched_count, eocd + 10, 1)
    assert_failure(
        inspect(mismatched_count), ArtifactBoundary.ARCHIVE, ArtifactFailureCode.MALFORMED
    )


def test_classic_zip_rejects_multi_disk_and_inconsistent_directory_offsets() -> None:
    payload = zip_bytes()
    eocd = len(payload) - 22
    multi_disk = patch_u16(payload, eocd + 4, 1)
    assert_failure(
        inspect(multi_disk),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSUPPORTED_ARCHIVE,
    )
    directory_offset = struct.unpack_from("<L", payload, eocd + 16)[0]
    bad_offset = patch_u32(payload, eocd + 16, cast(int, directory_offset) + 1)
    assert_failure(inspect(bad_offset), ArtifactBoundary.ARCHIVE, ArtifactFailureCode.MALFORMED)


def test_strict_zip64_rejects_malformed_and_multi_disk_extensions() -> None:
    payload = as_zip64(zip_bytes())
    eocd = len(payload) - 22
    locator = eocd - 20
    record = locator - 56

    minimal_eocd = bytearray(22)
    struct.pack_into(
        "<4s4H2LH",
        minimal_eocd,
        0,
        b"PK\x05\x06",
        0,
        0,
        0xFFFF,
        0xFFFF,
        0xFFFFFFFF,
        0xFFFFFFFF,
        0,
    )
    assert_failure(
        inspect(bytes(minimal_eocd)), ArtifactBoundary.ARCHIVE, ArtifactFailureCode.MALFORMED
    )

    mutations = (
        (
            bytes(bytearray(payload[:locator]) + b"bad!" + payload[locator + 4 :]),
            ArtifactFailureCode.MALFORMED,
        ),
        (patch_u32(payload, locator + 4, 1), ArtifactFailureCode.UNSUPPORTED_ARCHIVE),
        (
            bytes(bytearray(payload[:record]) + b"bad!" + payload[record + 4 :]),
            ArtifactFailureCode.MALFORMED,
        ),
        (patch_u32(payload, record + 4, 43), ArtifactFailureCode.MALFORMED),
        (patch_u16(payload, record + 14, 46), ArtifactFailureCode.UNSUPPORTED_ARCHIVE),
        (patch_u32(payload, record + 16, 1), ArtifactFailureCode.UNSUPPORTED_ARCHIVE),
        (patch_u32(payload, record + 48, 1), ArtifactFailureCode.MALFORMED),
        (patch_u16(payload, eocd + 8, 1), ArtifactFailureCode.MALFORMED),
    )
    for changed, code in mutations:
        assert_failure(inspect(changed), ArtifactBoundary.ARCHIVE, code)

    padded = payload[:locator] + b"x" + payload[locator:]
    assert_failure(inspect(padded), ArtifactBoundary.ARCHIVE, ArtifactFailureCode.MALFORMED)


def test_low_level_zip_defences_reject_invalid_metadata_and_reads() -> None:
    info = ZipInfo("Metadata/bad")
    info.file_size = -1
    with pytest.raises(validation._Denied):
        validation._validate_zip_info(info)

    directory = ZipInfo("Metadata/")
    directory.compress_type = ZIP_DEFLATED
    directory.header_offset = 0
    with pytest.raises(validation._Denied):
        validation._validate_zip_info(directory)

    new_version = ZipInfo("Metadata/new-version")
    new_version.extract_version = 46
    new_version.header_offset = 0
    with pytest.raises(validation._Denied):
        validation._validate_zip_info(new_version)

    old_version_unknown_compression = ZipInfo("Metadata/unknown-compression")
    old_version_unknown_compression.extract_version = 20
    old_version_unknown_compression.compress_type = ZIP_BZIP2
    old_version_unknown_compression.header_offset = 0
    with pytest.raises(validation._Denied):
        validation._validate_zip_info(old_version_unknown_compression)

    class BrokenSeek(BytesIO):
        def seek(self, pos: int, whence: int = 0) -> int:
            raise OSError("hostile")

    with pytest.raises(validation._Denied):
        validation._read_exact_at(cast(validation._ImmutableBytesReader, BrokenSeek()), 0, 1)
    with pytest.raises(validation._Denied):
        validation._read_exact_at(validation._ImmutableBytesReader(b""), -1, 1)
    with pytest.raises(validation._Denied):
        validation._read_exact_at(validation._ImmutableBytesReader(b"x"), 0, 2)


def test_immutable_reader_has_bounded_standard_seek_semantics() -> None:
    reader = validation._ImmutableBytesReader(b"abcdef")

    assert reader.read() == b"abcdef"
    assert reader.seek(-2, 1) == 4
    assert reader.read(1) == b"e"
    assert reader.tell() == 5
    assert reader.seekable()
    with pytest.raises(ValueError, match="unsupported whence"):
        reader.seek(0, 3)
    with pytest.raises(ValueError, match="negative seek"):
        reader.seek(-7)


def test_central_directory_cap_is_checked_before_zipfile_parsing() -> None:
    payload = zip_bytes()
    limits = ArtifactLimits(max_zip_metadata_bytes=22)

    assert_failure(
        inspect(payload, limits=limits),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )


def test_conflicting_local_header_and_selected_crc_failure_are_bounded() -> None:
    payload = zip_bytes()
    with ZipFile(BytesIO(payload)) as bundle:
        selected = next(info for info in bundle.infolist() if info.filename == SELECTED_PATH)
    local = selected.header_offset
    changed_header = bytearray(payload)
    changed_header[local + 30] ^= 1
    assert_failure(
        inspect(bytes(changed_header)),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.MALFORMED,
    )

    name_size, extra_size = struct.unpack_from("<2H", payload, local + 26)
    data_offset = local + 30 + name_size + extra_size
    corrupted = bytearray(payload)
    corrupted[data_offset + selected.compress_size // 2] ^= 1
    assert_failure(
        inspect(bytes(corrupted)),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.INTEGRITY_FAILED,
    )
