from __future__ import annotations

import hashlib
from io import BytesIO
from pathlib import Path
from typing import cast
from zipfile import ZIP_DEFLATED, ZIP_STORED, ZipFile, ZipInfo

import pytest

import klove.domain.artifact_validation as validation
from klove.domain.artifacts import (
    ArtifactBoundary,
    ArtifactFailure,
    ArtifactFailureCode,
    ArtifactIntent,
    ArtifactLimits,
)

FIXTURES = Path(__file__).parents[1] / "fixtures" / "artifacts"
SELECTED_PATH = "Metadata/plate_1.gcode"
VALID_GCODE = b"; generated by OrcaSlicer 2.3.0\nG28\nG1 X1.0 Y2.0\n"
CORE_ENTRIES = (
    ("[Content_Types].xml", b"<Types/>"),
    ("_rels/.rels", b"<Relationships/>"),
    ("3D/3dmodel.model", b"<model/>"),
)


def base_intent() -> ArtifactIntent:
    return ArtifactIntent.model_validate_json(
        (FIXTURES / "accepted-intent.json").read_text(encoding="utf-8")
    )


def zip_bytes(
    entries: list[tuple[str | ZipInfo, bytes]] | None = None,
    *,
    compression: int = ZIP_DEFLATED,
    archive_comment: bytes = b"",
) -> bytes:
    members: list[tuple[str | ZipInfo, bytes]] = list(CORE_ENTRIES)
    members.append((SELECTED_PATH, VALID_GCODE))
    if entries is not None:
        members = entries
    target = BytesIO()
    with ZipFile(target, mode="w", compression=compression, allowZip64=True) as bundle:
        for name, content in members:
            bundle.writestr(name, content)
        bundle.comment = archive_comment
    return target.getvalue()


def intent_for(payload: bytes, *, archive_path: str = SELECTED_PATH) -> ArtifactIntent:
    request = base_intent()
    return request.model_copy(
        update={
            "artifact": request.artifact.model_copy(
                update={
                    "archive_sha256": "sha256:" + hashlib.sha256(payload).hexdigest(),
                    "compressed_size_bytes": len(payload),
                }
            ),
            "selected_plate": request.selected_plate.model_copy(
                update={"archive_path": archive_path}
            ),
        }
    )


def inspect(payload: bytes, *, limits: ArtifactLimits | None = None) -> object:
    return validation.inspect_gcode_3mf(
        intent_for(payload),
        payload,
        limits=limits or ArtifactLimits(),
    )


def assert_failure(
    result: object,
    boundary: ArtifactBoundary,
    code: ArtifactFailureCode,
) -> None:
    assert result == ArtifactFailure(boundary=boundary, code=code)


def test_selected_reader_rejects_non_binary_oversized_and_short_sources() -> None:
    selected = ZipInfo(SELECTED_PATH)
    selected.file_size = 2

    class Source:
        def __init__(self, values: list[bytes]) -> None:
            self.values = iter(values)

        def __enter__(self) -> Source:
            return self

        def __exit__(self, *_args: object) -> None:
            return None

        def read(self, _size: int = -1) -> bytes:
            return next(self.values, b"")

    class Bundle:
        def __init__(self, source: Source) -> None:
            self.source = source

        def open(self, _info: ZipInfo, mode: str = "r") -> Source:
            assert mode == "r"
            return self.source

    bad_sources = (
        Source([cast(bytes, bytearray(b"x"))]),
        Source([b"xxx"]),
        Source([b"x"]),
    )
    for source in bad_sources:
        with pytest.raises(validation._Denied):
            validation._read_selected_gcode(
                cast(ZipFile, Bundle(source)), selected, ArtifactLimits()
            )


@pytest.mark.parametrize(
    ("gcode", "code"),
    [
        (b"; generated by OrcaSlicer\nG1 X1\x00\n", ArtifactFailureCode.INVALID_GCODE),
        (b"; generated by OrcaSlicer\rG1 X1\n", ArtifactFailureCode.INVALID_GCODE),
        (b"; generated by OrcaSlicer\nG1 X1\r", ArtifactFailureCode.INVALID_GCODE),
        (b"; generated by OrcaSlicer\nM104 S200\n", ArtifactFailureCode.INVALID_GCODE),
        (b"G1 X1\n", ArtifactFailureCode.INVALID_GCODE),
        (b"; generated by BambuStudio\nG1 X1\n", ArtifactFailureCode.INCOMPATIBLE_GCODE),
        (
            b"; generated by OrcaSlicer\nM1002 gcode_claim_action : 1\nG1 X1\n",
            ArtifactFailureCode.INCOMPATIBLE_GCODE,
        ),
        (
            b"; generated by OrcaSlicer\nN1M1002 gcode_claim_action : 1\nG1 X1\n",
            ArtifactFailureCode.INCOMPATIBLE_GCODE,
        ),
        (
            b"; generated by OrcaSlicer\nN1M620 S1\nG1 X1\n",
            ArtifactFailureCode.INCOMPATIBLE_GCODE,
        ),
        (
            b"; generated by OrcaSlicer\nN1T1000\nG1 X1\n",
            ArtifactFailureCode.INCOMPATIBLE_GCODE,
        ),
        (
            b"; generated by OrcaSlicer\n/N1M1002 gcode_claim_action : 1\nG1 X1\n",
            ArtifactFailureCode.INCOMPATIBLE_GCODE,
        ),
        (b"; generated by OrcaSlicer\nM622.1 S1\nG1 X1\n", ArtifactFailureCode.INCOMPATIBLE_GCODE),
        (b"; generated by OrcaSlicer\nT1000\nG1 X1\n", ArtifactFailureCode.INCOMPATIBLE_GCODE),
        (b"G28\n; generated by OrcaSlicer\nG1 X1\n", ArtifactFailureCode.INVALID_GCODE),
    ],
)
def test_invalid_and_known_bambu_only_gcode_are_denied(
    gcode: bytes, code: ArtifactFailureCode
) -> None:
    payload = zip_bytes([*CORE_ENTRIES, (SELECTED_PATH, gcode)])

    assert_failure(inspect(payload), ArtifactBoundary.SELECTED_PLATE, code)


def test_gcode_comments_do_not_execute_bambu_tokens_and_crlf_is_supported() -> None:
    gcode = (
        b"; generated by PrusaSlicer\r\n"
        b"; M1002 is just text\r\n"
        b"SET_PRINT_STATS_INFO TOTAL_LAYER=1\r\n"
        b"G1X1 Y2\r\n"
    )
    payload = zip_bytes([*CORE_ENTRIES, (SELECTED_PATH, gcode)])

    result = inspect(payload)

    assert isinstance(result, validation.ValidatedGcodeCandidate)
    assert result.source_archive is payload

    no_final_newline = b"; generated by OrcaSlicer\nG1 X1"
    no_final_newline_payload = zip_bytes([*CORE_ENTRIES, (SELECTED_PATH, no_final_newline)])
    assert isinstance(inspect(no_final_newline_payload), validation.ValidatedGcodeCandidate)


def test_gcode_header_and_line_limits_are_enforced() -> None:
    long_header = b"; generated by SuperSlicer\n" + b";" + b"x" * 80 + b"\nG1 X1\n"
    header_payload = zip_bytes([*CORE_ENTRIES, (SELECTED_PATH, long_header)])
    assert_failure(
        inspect(
            header_payload,
            limits=ArtifactLimits(max_gcode_header_bytes=64, max_gcode_line_bytes=128),
        ),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )
    long_line = b"; generated by OrcaSlicer\nG1 X" + b"1" * 80 + b"\n"
    line_payload = zip_bytes([*CORE_ENTRIES, (SELECTED_PATH, long_line)])
    assert_failure(
        inspect(
            line_payload,
            limits=ArtifactLimits(max_gcode_header_bytes=64, max_gcode_line_bytes=32),
        ),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )


def test_bambu_signature_split_across_decompression_chunks_is_denied() -> None:
    prefix = b"; generated by OrcaSlicer\nG1 X1\n"
    padding = b"; bounded filler 0123456789\n" * 2600
    assert len(prefix) + len(padding) > 64 * 1024
    gcode = prefix + padding + b"N1M1002 gcode_claim_action : 1\n"
    payload = zip_bytes([*CORE_ENTRIES, (SELECTED_PATH, gcode)], compression=ZIP_STORED)

    assert_failure(
        inspect(payload),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.INCOMPATIBLE_GCODE,
    )
