from __future__ import annotations

import hashlib
import stat
import struct
from dataclasses import replace
from io import BytesIO
from pathlib import Path
from typing import cast
from zipfile import ZIP_BZIP2, ZIP_DEFLATED, ZIP_STORED, ZipFile, ZipInfo

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

import klove.domain.artifact_validation as validation
from klove.domain.artifact_validation import (
    ValidatedGcodeCandidate,
    inspect_gcode_3mf,
    open_selected_gcode,
)
from klove.domain.artifacts import (
    ArtifactBoundary,
    ArtifactFailure,
    ArtifactFailureCode,
    ArtifactIntent,
    ArtifactLimits,
)

FIXTURES = Path(__file__).parents[1] / "fixtures" / "artifacts"
SELECTED_PATH = "Metadata/plate_1.gcode"
VALID_GCODE = b"; generated by OrcaSlicer 2.3.0\nG28\nG1 X1.0 Y2.0\n"
CORE_ENTRIES = (
    ("[Content_Types].xml", b"<Types/>"),
    ("_rels/.rels", b"<Relationships/>"),
    ("3D/3dmodel.model", b"<model/>"),
)


def base_intent() -> ArtifactIntent:
    return ArtifactIntent.model_validate_json(
        (FIXTURES / "accepted-intent.json").read_text(encoding="utf-8")
    )


def zip_bytes(
    entries: list[tuple[str | ZipInfo, bytes]] | None = None,
    *,
    compression: int = ZIP_DEFLATED,
    archive_comment: bytes = b"",
) -> bytes:
    members: list[tuple[str | ZipInfo, bytes]] = list(CORE_ENTRIES)
    members.append((SELECTED_PATH, VALID_GCODE))
    if entries is not None:
        members = entries
    target = BytesIO()
    with ZipFile(target, mode="w", compression=compression, allowZip64=True) as bundle:
        for name, content in members:
            bundle.writestr(name, content)
        bundle.comment = archive_comment
    return target.getvalue()


def intent_for(payload: bytes, *, archive_path: str = SELECTED_PATH) -> ArtifactIntent:
    request = base_intent()
    return request.model_copy(
        update={
            "artifact": request.artifact.model_copy(
                update={
                    "archive_sha256": "sha256:" + hashlib.sha256(payload).hexdigest(),
                    "compressed_size_bytes": len(payload),
                }
            ),
            "selected_plate": request.selected_plate.model_copy(
                update={"archive_path": archive_path}
            ),
        }
    )


def inspect(payload: bytes, *, limits: ArtifactLimits | None = None) -> object:
    return inspect_gcode_3mf(
        intent_for(payload),
        payload,
        limits=limits or ArtifactLimits(),
    )


def assert_failure(
    result: object,
    boundary: ArtifactBoundary,
    code: ArtifactFailureCode,
) -> None:
    assert result == ArtifactFailure(boundary=boundary, code=code)


def central_record_offset(payload: bytes, name: str) -> int:
    eocd = len(payload) - 22
    directory_offset = cast(int, struct.unpack_from("<L", payload, eocd + 16)[0])
    offset = directory_offset
    while payload[offset : offset + 4] == b"PK\x01\x02":
        name_size, extra_size, comment_size = struct.unpack_from("<3H", payload, offset + 28)
        current = payload[offset + 46 : offset + 46 + name_size].decode("utf-8")
        if current == name:
            return offset
        offset += 46 + name_size + extra_size + comment_size
    raise AssertionError(name)


def patch_u16(payload: bytes, offset: int, value: int) -> bytes:
    changed = bytearray(payload)
    struct.pack_into("<H", changed, offset, value)
    return bytes(changed)


def patch_u32(payload: bytes, offset: int, value: int) -> bytes:
    changed = bytearray(payload)
    struct.pack_into("<L", changed, offset, value)
    return bytes(changed)


def as_zip64(payload: bytes) -> bytes:
    eocd_offset = len(payload) - 22
    eocd = bytearray(payload[eocd_offset:])
    entries = struct.unpack_from("<H", eocd, 10)[0]
    directory_size = struct.unpack_from("<L", eocd, 12)[0]
    directory_offset = struct.unpack_from("<L", eocd, 16)[0]
    record = struct.pack(
        "<4sQ2H2L4Q",
        b"PK\x06\x06",
        44,
        45,
        45,
        0,
        0,
        entries,
        entries,
        directory_size,
        directory_offset,
    )
    locator = struct.pack("<4sLQL", b"PK\x06\x07", 0, eocd_offset, 1)
    struct.pack_into("<4H2L", eocd, 4, 0, 0, 0xFFFF, 0xFFFF, 0xFFFFFFFF, 0xFFFFFFFF)
    return payload[:eocd_offset] + record + locator + bytes(eocd)


def test_valid_archive_returns_byte_exact_candidate_and_observed_evidence() -> None:
    entries: list[tuple[str | ZipInfo, bytes]] = [
        ("Metadata/", b""),
        ("3D/", b""),
        *CORE_ENTRIES,
        ("Metadata/readme.txt", b"metadata"),
        (SELECTED_PATH, VALID_GCODE),
    ]
    for index, (name, content) in enumerate(entries):
        if isinstance(name, str) and name.endswith("/"):
            info = ZipInfo(name)
            info.create_system = 3
            info.external_attr = (stat.S_IFDIR | 0o755) << 16 | 0x10
            info.compress_type = ZIP_STORED
            entries[index] = (info, content)
    payload = zip_bytes(entries)
    result = inspect_gcode_3mf(intent_for(payload), payload, limits=ArtifactLimits())

    assert isinstance(result, ValidatedGcodeCandidate)
    assert result.source_archive is payload
    assert result.inspection.artifact == intent_for(payload).artifact
    assert not hasattr(result.inspection, "target")
    assert result.inspection.selected_plate.archive_path == SELECTED_PATH
    assert result.inspection.selected_plate.gcode_sha256 == (
        "sha256:" + hashlib.sha256(VALID_GCODE).hexdigest()
    )
    with ZipFile(BytesIO(payload)) as bundle:
        infos = bundle.infolist()
    assert result.inspection.zip_entry_count == len(infos)
    assert result.inspection.archive_expanded_bytes == sum(info.file_size for info in infos)
    assert "source_archive" not in repr(result)


def test_selected_gcode_can_only_reopen_the_exact_inspected_member() -> None:
    payload = zip_bytes()
    candidate = inspect(payload)
    assert isinstance(candidate, ValidatedGcodeCandidate)

    with open_selected_gcode(candidate) as selected:
        assert selected.read() == VALID_GCODE

    missing = replace(
        candidate,
        inspection=candidate.inspection.model_copy(
            update={
                "selected_plate": candidate.inspection.selected_plate.model_copy(
                    update={"archive_path": "Metadata/missing.gcode"}
                )
            }
        ),
    )
    wrong_size = replace(
        candidate,
        inspection=candidate.inspection.model_copy(
            update={
                "selected_plate": candidate.inspection.selected_plate.model_copy(
                    update={"gcode_size_bytes": len(VALID_GCODE) + 1}
                )
            }
        ),
    )
    malformed = replace(candidate, source_archive=b"not-a-zip")
    for value in (missing, wrong_size, malformed):
        with (
            pytest.raises(ValueError, match="selected member is unavailable"),
            open_selected_gcode(value),
        ):
            raise AssertionError("unreachable")


def test_valid_strict_zip64_archive_is_supported() -> None:
    payload = as_zip64(zip_bytes())

    assert isinstance(inspect(payload), ValidatedGcodeCandidate)


@pytest.mark.parametrize(
    ("archive", "limits", "code"),
    [
        (b"not-a-zip", ArtifactLimits(), ArtifactFailureCode.MALFORMED),
        (zip_bytes(archive_comment=b"comment"), ArtifactLimits(), ArtifactFailureCode.MALFORMED),
        (
            zip_bytes(),
            ArtifactLimits(max_archive_compressed_bytes=22),
            ArtifactFailureCode.LIMIT_EXCEEDED,
        ),
    ],
)
def test_truncated_commented_and_oversized_archives_are_denied(
    archive: bytes, limits: ArtifactLimits, code: ArtifactFailureCode
) -> None:
    assert_failure(
        inspect(archive, limits=limits),
        ArtifactBoundary.ARCHIVE
        if code is ArtifactFailureCode.MALFORMED
        else ArtifactBoundary.INTAKE,
        code,
    )


def test_intake_requires_exact_size_digest_and_immutable_bytes_snapshot() -> None:
    payload = zip_bytes()
    request = intent_for(payload)
    wrong_size = request.model_copy(
        update={
            "artifact": request.artifact.model_copy(
                update={"compressed_size_bytes": len(payload) + 1}
            )
        }
    )
    assert_failure(
        inspect_gcode_3mf(wrong_size, payload, limits=ArtifactLimits()),
        ArtifactBoundary.INTAKE,
        ArtifactFailureCode.INTEGRITY_FAILED,
    )
    wrong_digest = request.model_copy(
        update={
            "artifact": request.artifact.model_copy(update={"archive_sha256": "sha256:" + "0" * 64})
        }
    )
    assert_failure(
        inspect_gcode_3mf(wrong_digest, payload, limits=ArtifactLimits()),
        ArtifactBoundary.INTAKE,
        ArtifactFailureCode.INTEGRITY_FAILED,
    )

    assert_failure(
        inspect_gcode_3mf(
            request,
            cast(bytes, bytearray(payload)),
            limits=ArtifactLimits(),
        ),
        ArtifactBoundary.INTAKE,
        ArtifactFailureCode.UNSUPPORTED_ARCHIVE,
    )


def test_parser_fallback_maps_unexpected_zipfile_failure_to_malformed(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    payload = zip_bytes()

    def broken_zipfile(*_args: object, **_kwargs: object) -> ZipFile:
        raise OSError("hostile secret")

    monkeypatch.setattr(validation, "ZipFile", broken_zipfile)
    result = inspect(payload)

    assert_failure(result, ArtifactBoundary.ARCHIVE, ArtifactFailureCode.MALFORMED)
    assert "hostile secret" not in cast(ArtifactFailure, result).model_dump_json()


@pytest.mark.parametrize(
    "name",
    [
        "../escape.gcode",
        "/absolute.gcode",
        "Metadata\\plate.gcode",
        "C:/Metadata/plate.gcode",
        "Metadata//plate.gcode",
        "Metadata/./plate.gcode",
        "Metadata/../plate.gcode",
        "Metadata/ plate.gcode",
        "Metadata/tab\tplate.gcode",
        "Metadata/pl\u00e1te.gcode",
    ],
)
def test_unsafe_member_names_are_denied(name: str) -> None:
    payload = zip_bytes([*CORE_ENTRIES, (name, b"unselected"), (SELECTED_PATH, VALID_GCODE)])

    assert_failure(
        inspect(payload),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSAFE_ARCHIVE,
    )


def test_nul_sanitized_duplicate_and_case_alias_names_are_denied() -> None:
    payload = zip_bytes()
    central = central_record_offset(payload, SELECTED_PATH)
    with ZipFile(BytesIO(payload)) as bundle:
        local = next(
            info.header_offset for info in bundle.infolist() if info.filename == SELECTED_PATH
        )
    nul_payload = bytearray(payload)
    nul_index = len("Metadata/plate_1")
    nul_payload[central + 46 + nul_index] = 0
    nul_payload[local + 30 + nul_index] = 0
    assert_failure(
        inspect(bytes(nul_payload)),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSAFE_ARCHIVE,
    )

    with pytest.warns(UserWarning, match="Duplicate name"):
        duplicate = zip_bytes(
            [*CORE_ENTRIES, (SELECTED_PATH, VALID_GCODE), (SELECTED_PATH, VALID_GCODE)]
        )
    assert_failure(
        inspect(duplicate),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSAFE_ARCHIVE,
    )
    case_alias = zip_bytes(
        [
            *CORE_ENTRIES,
            ("Metadata/readme.txt", b"a"),
            ("metadata/README.TXT", b"b"),
            (SELECTED_PATH, VALID_GCODE),
        ]
    )
    assert_failure(
        inspect(case_alias),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSAFE_ARCHIVE,
    )


def test_links_encryption_and_unsupported_zip_features_are_denied() -> None:
    link = ZipInfo("Metadata/link")
    link.create_system = 3
    link.external_attr = (stat.S_IFLNK | 0o777) << 16
    linked = zip_bytes([*CORE_ENTRIES, (link, b"target"), (SELECTED_PATH, VALID_GCODE)])
    assert_failure(inspect(linked), ArtifactBoundary.ARCHIVE, ArtifactFailureCode.UNSAFE_ARCHIVE)

    payload = zip_bytes()
    central = central_record_offset(payload, SELECTED_PATH)
    with ZipFile(BytesIO(payload)) as bundle:
        local = next(
            info.header_offset for info in bundle.infolist() if info.filename == SELECTED_PATH
        )
    encrypted = patch_u16(payload, central + 8, 1)
    encrypted = patch_u16(encrypted, local + 6, 1)
    assert_failure(inspect(encrypted), ArtifactBoundary.ARCHIVE, ArtifactFailureCode.UNSAFE_ARCHIVE)

    unsupported = zip_bytes(compression=ZIP_BZIP2)
    assert_failure(
        inspect(unsupported),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSUPPORTED_ARCHIVE,
    )

    unsupported_flags = patch_u16(payload, central + 8, 1 << 4)
    assert_failure(
        inspect(unsupported_flags),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSUPPORTED_ARCHIVE,
    )

    commented = ZipInfo("Metadata/commented")
    commented.comment = b"comment"
    with_comment = zip_bytes([*CORE_ENTRIES, (commented, b"content"), (SELECTED_PATH, VALID_GCODE)])
    assert_failure(
        inspect(with_comment),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSUPPORTED_ARCHIVE,
    )

    volume = patch_u16(payload, central + 34, 1)
    assert_failure(
        inspect(volume),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSUPPORTED_ARCHIVE,
    )


def test_missing_3mf_parts_or_exact_selected_plate_are_denied_without_inference() -> None:
    not_3mf = zip_bytes([(SELECTED_PATH, VALID_GCODE)])
    assert_failure(
        inspect(not_3mf),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSUPPORTED_ARCHIVE,
    )
    geometry_only = zip_bytes(list(CORE_ENTRIES))
    assert_failure(
        inspect(geometry_only),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.EVIDENCE_MISSING,
    )
    other_plate = zip_bytes([*CORE_ENTRIES, ("Metadata/plate_2.gcode", VALID_GCODE)])
    assert_failure(
        inspect(other_plate),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.EVIDENCE_MISSING,
    )


def test_entry_count_expanded_size_ratio_and_selected_size_limits_are_enforced() -> None:
    payload = zip_bytes()
    assert_failure(
        inspect(payload, limits=ArtifactLimits(max_zip_entries=1)),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )

    central = central_record_offset(payload, SELECTED_PATH)
    zero_compressed_size = patch_u32(payload, central + 20, 0)
    assert_failure(
        inspect(zero_compressed_size),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )
    assert_failure(
        inspect(
            payload,
            limits=ArtifactLimits(
                max_archive_expanded_bytes=64,
                max_gcode_bytes=64,
                max_gcode_header_bytes=64,
                max_gcode_line_bytes=64,
            ),
        ),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )
    bomb = zip_bytes(
        [*CORE_ENTRIES, ("Metadata/padding", b"A" * 4096), (SELECTED_PATH, VALID_GCODE)]
    )
    assert_failure(
        inspect(bomb, limits=ArtifactLimits(max_compression_ratio=2)),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )
    large_gcode_payload = zip_bytes(
        [*CORE_ENTRIES, (SELECTED_PATH, VALID_GCODE + b"; filler\n" * 10)]
    )
    assert_failure(
        inspect(
            large_gcode_payload,
            limits=ArtifactLimits(
                max_gcode_bytes=64,
                max_gcode_header_bytes=64,
                max_gcode_line_bytes=32,
            ),
        ),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )


def test_empty_archive_empty_selected_member_and_declared_entry_mismatch_are_denied() -> None:
    empty_archive = zip_bytes([])
    assert_failure(inspect(empty_archive), ArtifactBoundary.ARCHIVE, ArtifactFailureCode.MALFORMED)

    empty_selected = zip_bytes([*CORE_ENTRIES, (SELECTED_PATH, b"")])
    assert_failure(
        inspect(empty_selected),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.INVALID_GCODE,
    )

    payload = zip_bytes()
    eocd = len(payload) - 22
    mismatched_count = patch_u16(payload, eocd + 8, 1)
    mismatched_count = patch_u16(mismatched_count, eocd + 10, 1)
    assert_failure(
        inspect(mismatched_count), ArtifactBoundary.ARCHIVE, ArtifactFailureCode.MALFORMED
    )


def test_classic_zip_rejects_multi_disk_and_inconsistent_directory_offsets() -> None:
    payload = zip_bytes()
    eocd = len(payload) - 22
    multi_disk = patch_u16(payload, eocd + 4, 1)
    assert_failure(
        inspect(multi_disk),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.UNSUPPORTED_ARCHIVE,
    )
    directory_offset = struct.unpack_from("<L", payload, eocd + 16)[0]
    bad_offset = patch_u32(payload, eocd + 16, cast(int, directory_offset) + 1)
    assert_failure(inspect(bad_offset), ArtifactBoundary.ARCHIVE, ArtifactFailureCode.MALFORMED)


def test_strict_zip64_rejects_malformed_and_multi_disk_extensions() -> None:
    payload = as_zip64(zip_bytes())
    eocd = len(payload) - 22
    locator = eocd - 20
    record = locator - 56

    minimal_eocd = bytearray(22)
    struct.pack_into(
        "<4s4H2LH",
        minimal_eocd,
        0,
        b"PK\x05\x06",
        0,
        0,
        0xFFFF,
        0xFFFF,
        0xFFFFFFFF,
        0xFFFFFFFF,
        0,
    )
    assert_failure(
        inspect(bytes(minimal_eocd)), ArtifactBoundary.ARCHIVE, ArtifactFailureCode.MALFORMED
    )

    mutations = (
        (
            bytes(bytearray(payload[:locator]) + b"bad!" + payload[locator + 4 :]),
            ArtifactFailureCode.MALFORMED,
        ),
        (patch_u32(payload, locator + 4, 1), ArtifactFailureCode.UNSUPPORTED_ARCHIVE),
        (
            bytes(bytearray(payload[:record]) + b"bad!" + payload[record + 4 :]),
            ArtifactFailureCode.MALFORMED,
        ),
        (patch_u32(payload, record + 4, 43), ArtifactFailureCode.MALFORMED),
        (patch_u16(payload, record + 14, 46), ArtifactFailureCode.UNSUPPORTED_ARCHIVE),
        (patch_u32(payload, record + 16, 1), ArtifactFailureCode.UNSUPPORTED_ARCHIVE),
        (patch_u32(payload, record + 48, 1), ArtifactFailureCode.MALFORMED),
        (patch_u16(payload, eocd + 8, 1), ArtifactFailureCode.MALFORMED),
    )
    for changed, code in mutations:
        assert_failure(inspect(changed), ArtifactBoundary.ARCHIVE, code)

    padded = payload[:locator] + b"x" + payload[locator:]
    assert_failure(inspect(padded), ArtifactBoundary.ARCHIVE, ArtifactFailureCode.MALFORMED)


def test_low_level_zip_defences_reject_invalid_metadata_and_reads() -> None:
    info = ZipInfo("Metadata/bad")
    info.file_size = -1
    with pytest.raises(validation._Denied):
        validation._validate_zip_info(info)

    directory = ZipInfo("Metadata/")
    directory.compress_type = ZIP_DEFLATED
    directory.header_offset = 0
    with pytest.raises(validation._Denied):
        validation._validate_zip_info(directory)

    new_version = ZipInfo("Metadata/new-version")
    new_version.extract_version = 46
    new_version.header_offset = 0
    with pytest.raises(validation._Denied):
        validation._validate_zip_info(new_version)

    old_version_unknown_compression = ZipInfo("Metadata/unknown-compression")
    old_version_unknown_compression.extract_version = 20
    old_version_unknown_compression.compress_type = ZIP_BZIP2
    old_version_unknown_compression.header_offset = 0
    with pytest.raises(validation._Denied):
        validation._validate_zip_info(old_version_unknown_compression)

    class BrokenSeek(BytesIO):
        def seek(self, pos: int, whence: int = 0) -> int:
            raise OSError("hostile")

    with pytest.raises(validation._Denied):
        validation._read_exact_at(cast(validation._ImmutableBytesReader, BrokenSeek()), 0, 1)
    with pytest.raises(validation._Denied):
        validation._read_exact_at(validation._ImmutableBytesReader(b""), -1, 1)
    with pytest.raises(validation._Denied):
        validation._read_exact_at(validation._ImmutableBytesReader(b"x"), 0, 2)


def test_immutable_reader_has_bounded_standard_seek_semantics() -> None:
    reader = validation._ImmutableBytesReader(b"abcdef")

    assert reader.read() == b"abcdef"
    assert reader.seek(-2, 1) == 4
    assert reader.read(1) == b"e"
    assert reader.tell() == 5
    assert reader.seekable()
    with pytest.raises(ValueError, match="unsupported whence"):
        reader.seek(0, 3)
    with pytest.raises(ValueError, match="negative seek"):
        reader.seek(-7)


def test_selected_reader_rejects_non_binary_oversized_and_short_sources() -> None:
    selected = ZipInfo(SELECTED_PATH)
    selected.file_size = 2

    class Source:
        def __init__(self, values: list[bytes]) -> None:
            self.values = iter(values)

        def __enter__(self) -> Source:
            return self

        def __exit__(self, *_args: object) -> None:
            return None

        def read(self, _size: int = -1) -> bytes:
            return next(self.values, b"")

    class Bundle:
        def __init__(self, source: Source) -> None:
            self.source = source

        def open(self, _info: ZipInfo, mode: str = "r") -> Source:
            assert mode == "r"
            return self.source

    bad_sources = (
        Source([cast(bytes, bytearray(b"x"))]),
        Source([b"xxx"]),
        Source([b"x"]),
    )
    for source in bad_sources:
        with pytest.raises(validation._Denied):
            validation._read_selected_gcode(
                cast(ZipFile, Bundle(source)), selected, ArtifactLimits()
            )


def test_central_directory_cap_is_checked_before_zipfile_parsing() -> None:
    payload = zip_bytes()
    limits = ArtifactLimits(max_zip_metadata_bytes=22)

    assert_failure(
        inspect(payload, limits=limits),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )


def test_conflicting_local_header_and_selected_crc_failure_are_bounded() -> None:
    payload = zip_bytes()
    with ZipFile(BytesIO(payload)) as bundle:
        selected = next(info for info in bundle.infolist() if info.filename == SELECTED_PATH)
    local = selected.header_offset
    changed_header = bytearray(payload)
    changed_header[local + 30] ^= 1
    assert_failure(
        inspect(bytes(changed_header)),
        ArtifactBoundary.ARCHIVE,
        ArtifactFailureCode.MALFORMED,
    )

    name_size, extra_size = struct.unpack_from("<2H", payload, local + 26)
    data_offset = local + 30 + name_size + extra_size
    corrupted = bytearray(payload)
    corrupted[data_offset + selected.compress_size // 2] ^= 1
    assert_failure(
        inspect(bytes(corrupted)),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.INTEGRITY_FAILED,
    )


@pytest.mark.parametrize(
    ("gcode", "code"),
    [
        (b"; generated by OrcaSlicer\nG1 X1\x00\n", ArtifactFailureCode.INVALID_GCODE),
        (b"; generated by OrcaSlicer\rG1 X1\n", ArtifactFailureCode.INVALID_GCODE),
        (b"; generated by OrcaSlicer\nG1 X1\r", ArtifactFailureCode.INVALID_GCODE),
        (b"; generated by OrcaSlicer\nM104 S200\n", ArtifactFailureCode.INVALID_GCODE),
        (b"G1 X1\n", ArtifactFailureCode.INVALID_GCODE),
        (b"; generated by BambuStudio\nG1 X1\n", ArtifactFailureCode.INCOMPATIBLE_GCODE),
        (
            b"; generated by OrcaSlicer\nM1002 gcode_claim_action : 1\nG1 X1\n",
            ArtifactFailureCode.INCOMPATIBLE_GCODE,
        ),
        (
            b"; generated by OrcaSlicer\nN1M1002 gcode_claim_action : 1\nG1 X1\n",
            ArtifactFailureCode.INCOMPATIBLE_GCODE,
        ),
        (
            b"; generated by OrcaSlicer\nN1M620 S1\nG1 X1\n",
            ArtifactFailureCode.INCOMPATIBLE_GCODE,
        ),
        (
            b"; generated by OrcaSlicer\nN1T1000\nG1 X1\n",
            ArtifactFailureCode.INCOMPATIBLE_GCODE,
        ),
        (
            b"; generated by OrcaSlicer\n/N1M1002 gcode_claim_action : 1\nG1 X1\n",
            ArtifactFailureCode.INCOMPATIBLE_GCODE,
        ),
        (b"; generated by OrcaSlicer\nM622.1 S1\nG1 X1\n", ArtifactFailureCode.INCOMPATIBLE_GCODE),
        (b"; generated by OrcaSlicer\nT1000\nG1 X1\n", ArtifactFailureCode.INCOMPATIBLE_GCODE),
        (b"G28\n; generated by OrcaSlicer\nG1 X1\n", ArtifactFailureCode.INVALID_GCODE),
    ],
)
def test_invalid_and_known_bambu_only_gcode_are_denied(
    gcode: bytes, code: ArtifactFailureCode
) -> None:
    payload = zip_bytes([*CORE_ENTRIES, (SELECTED_PATH, gcode)])

    assert_failure(inspect(payload), ArtifactBoundary.SELECTED_PLATE, code)


def test_gcode_comments_do_not_execute_bambu_tokens_and_crlf_is_supported() -> None:
    gcode = (
        b"; generated by PrusaSlicer\r\n"
        b"; M1002 is just text\r\n"
        b"SET_PRINT_STATS_INFO TOTAL_LAYER=1\r\n"
        b"G1X1 Y2\r\n"
    )
    payload = zip_bytes([*CORE_ENTRIES, (SELECTED_PATH, gcode)])

    result = inspect(payload)

    assert isinstance(result, ValidatedGcodeCandidate)
    assert result.source_archive is payload

    no_final_newline = b"; generated by OrcaSlicer\nG1 X1"
    no_final_newline_payload = zip_bytes([*CORE_ENTRIES, (SELECTED_PATH, no_final_newline)])
    assert isinstance(inspect(no_final_newline_payload), ValidatedGcodeCandidate)


def test_gcode_header_and_line_limits_are_enforced() -> None:
    long_header = b"; generated by SuperSlicer\n" + b";" + b"x" * 80 + b"\nG1 X1\n"
    header_payload = zip_bytes([*CORE_ENTRIES, (SELECTED_PATH, long_header)])
    assert_failure(
        inspect(
            header_payload,
            limits=ArtifactLimits(max_gcode_header_bytes=64, max_gcode_line_bytes=128),
        ),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )
    long_line = b"; generated by OrcaSlicer\nG1 X" + b"1" * 80 + b"\n"
    line_payload = zip_bytes([*CORE_ENTRIES, (SELECTED_PATH, long_line)])
    assert_failure(
        inspect(
            line_payload,
            limits=ArtifactLimits(max_gcode_header_bytes=64, max_gcode_line_bytes=32),
        ),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.LIMIT_EXCEEDED,
    )


def test_bambu_signature_split_across_decompression_chunks_is_denied() -> None:
    prefix = b"; generated by OrcaSlicer\nG1 X1\n"
    padding = b"; bounded filler 0123456789\n" * 2600
    assert len(prefix) + len(padding) > 64 * 1024
    gcode = prefix + padding + b"N1M1002 gcode_claim_action : 1\n"
    payload = zip_bytes([*CORE_ENTRIES, (SELECTED_PATH, gcode)], compression=ZIP_STORED)

    assert_failure(
        inspect(payload),
        ArtifactBoundary.SELECTED_PLATE,
        ArtifactFailureCode.INCOMPATIBLE_GCODE,
    )


@settings(max_examples=40, deadline=None)
@given(st.binary(max_size=2048))
def test_arbitrary_zip_like_bytes_always_produce_a_bounded_result(payload: bytes) -> None:
    request = intent_for(payload or b"x")
    result = inspect_gcode_3mf(request, payload or b"x", limits=ArtifactLimits())

    assert isinstance(result, ArtifactFailure | ValidatedGcodeCandidate)
    if isinstance(result, ArtifactFailure):
        assert result.model_dump_json() in {
            ArtifactFailure(boundary=boundary, code=code).model_dump_json()
            for boundary in ArtifactBoundary
            for code in ArtifactFailureCode
        }
