from __future__ import annotations

import asyncio
import hashlib
from dataclasses import replace
from decimal import Decimal
from io import BytesIO
from pathlib import Path
from typing import BinaryIO
from zipfile import ZIP_DEFLATED, ZipFile

import pytest

import klove.orchestration.upload as upload_module
from klove.config import PrinterConfig
from klove.domain.artifact_validation import ValidatedGcodeCandidate, inspect_gcode_3mf
from klove.domain.artifacts import (
    CONTRACT_VERSION,
    ArtifactCompatibility,
    ArtifactIntent,
    ArtifactLimits,
    ArtifactQualification,
    BuildVolume,
    GcodeFlavor,
    PlateSelection,
    SafetyProfile,
    target_for_safety_profile,
)
from klove.domain.upload import (
    MoonrakerGcodeMetadata,
    MoonrakerUploadReceipt,
    RemoteFileDigest,
    UploadBoundary,
    UploadFailureCode,
    UploadOperationResult,
    UploadState,
)
from klove.errors import UploadTransportError
from klove.orchestration.upload import UploadService

FIXTURES = Path(__file__).parents[1] / "fixtures" / "artifacts"
GCODE = b"; generated by OrcaSlicer 2.3.0\nG28\nG1 X1 Y2\n"
SELECTED_PATH = "Metadata/plate_1.gcode"


def profile() -> SafetyProfile:
    return SafetyProfile(
        printer_uuid="11111111-1111-4111-8111-111111111111",
        generation=7,
        slicer_profile_id="klipper-voron-24-0.4",
        compatibility=ArtifactCompatibility(
            gcode_flavor=GcodeFlavor.KLIPPER,
            nozzle_diameter_micrometres=400,
            build_volume=BuildVolume(
                x_micrometres=350_000,
                y_micrometres=350_000,
                z_micrometres=350_000,
            ),
            build_plate_id="textured-pei",
        ),
    )


def archive_bytes() -> bytes:
    target = BytesIO()
    with ZipFile(target, mode="w", compression=ZIP_DEFLATED) as bundle:
        bundle.writestr("[Content_Types].xml", b"<Types/>")
        bundle.writestr("_rels/.rels", b"<Relationships/>")
        bundle.writestr("3D/3dmodel.model", b"<model/>")
        bundle.writestr(SELECTED_PATH, GCODE)
    return target.getvalue()


def candidate_and_qualification() -> tuple[ValidatedGcodeCandidate, ArtifactQualification]:
    payload = archive_bytes()
    accepted = ArtifactIntent.model_validate_json(
        (FIXTURES / "accepted-intent.json").read_text(encoding="utf-8")
    )
    artifact = accepted.artifact.model_copy(
        update={
            "archive_sha256": "sha256:" + hashlib.sha256(payload).hexdigest(),
            "compressed_size_bytes": len(payload),
        }
    )
    intent = ArtifactIntent(
        contract_version=CONTRACT_VERSION,
        operation_id=accepted.operation_id,
        idempotency_key=accepted.idempotency_key,
        artifact=artifact,
        selected_plate=PlateSelection(plate_id="1", archive_path=SELECTED_PATH),
        target=target_for_safety_profile(profile()),
    )
    inspected = inspect_gcode_3mf(intent, payload, limits=ArtifactLimits())
    assert isinstance(inspected, ValidatedGcodeCandidate)
    qualification = ArtifactQualification(
        approval_id="44444444-4444-4444-8444-444444444444",
        authority_id="grove-slicer-registry",
        operation_id=intent.operation_id,
        idempotency_key=intent.idempotency_key,
        artifact=artifact,
        selected_plate=inspected.inspection.selected_plate,
        target=intent.target,
    )
    return inspected, qualification


def printer(*, profiles: tuple[SafetyProfile, ...] | None = None) -> PrinterConfig:
    return PrinterConfig(
        id="voron",
        uuid=profile().printer_uuid,
        endpoint="http://127.0.0.1:7125",
        api_key_file=Path("unused"),
        safety_profiles=(profile(),) if profiles is None else profiles,
    )


class FakeClock:
    def __init__(self) -> None:
        self.now = 0.0

    def __call__(self) -> float:
        return self.now

    async def sleep(self, delay: float) -> None:
        self.now += delay


class FakeTransport:
    def __init__(self) -> None:
        self.uploads: list[tuple[str, bytes, str, int]] = []
        self.upload_entered = asyncio.Event()
        self.release_upload = asyncio.Event()
        self.release_upload.set()
        self.last_path = ""
        self.last_content = b""
        self.last_size = 0
        self.modified = Decimal("1700000000.25")
        self.metadata_values: list[MoonrakerGcodeMetadata | Exception | None] = []
        self.metadata_calls = 0
        self.upload_error = False
        self.download_error = False
        self.receipt_path: str | None = None
        self.receipt_size: int | None = None
        self.remote_size: int | None = None
        self.remote_digest: str | None = None

    async def upload(
        self, path: str, content: BinaryIO, sha256: str, size_bytes: int
    ) -> MoonrakerUploadReceipt:
        self.upload_entered.set()
        await self.release_upload.wait()
        value = content.read()
        self.uploads.append((path, value, sha256, size_bytes))
        self.last_path = path
        self.last_content = value
        self.last_size = size_bytes
        if self.upload_error:
            raise UploadTransportError
        return MoonrakerUploadReceipt(
            path=self.receipt_path or path,
            size_bytes=self.receipt_size or size_bytes,
            modified=self.modified,
        )

    async def metadata(self, path: str) -> MoonrakerGcodeMetadata | None:
        self.metadata_calls += 1
        if self.metadata_values:
            value = self.metadata_values.pop(0)
            if isinstance(value, Exception):
                raise value
            return value
        return self.metadata_for(path)

    def metadata_for(self, requested_path: str, **updates: object) -> MoonrakerGcodeMetadata:
        values: dict[str, object] = {
            "path": requested_path,
            "size_bytes": self.last_size,
            "modified": self.modified,
            "metadata_uuid": "55555555-5555-4555-8555-555555555555",
            "file_processors": (),
            "nozzle_diameter_micrometres": 400,
            "gcode_start_byte": 1,
            "gcode_end_byte": self.last_size,
            "job_id": None,
            "print_start_time": None,
        }
        values.update(updates)
        return MoonrakerGcodeMetadata.model_validate(values)

    async def download(self, path: str, expected_size: int) -> RemoteFileDigest:
        if self.download_error:
            raise UploadTransportError
        assert path == self.last_path
        assert expected_size == self.last_size
        return RemoteFileDigest(
            size_bytes=self.remote_size or len(self.last_content),
            sha256=self.remote_digest or "sha256:" + hashlib.sha256(self.last_content).hexdigest(),
        )


def service(
    transport: FakeTransport,
    *,
    configured_printer: PrinterConfig | None = None,
    capacity: int = 10,
    clock: FakeClock | None = None,
) -> UploadService:
    fake_clock = clock or FakeClock()
    return UploadService(
        configured_printer or printer(),
        transport,
        limits=ArtifactLimits(
            metadata_wait_seconds=0.2,
            metadata_poll_interval_seconds=0.1,
            upload_idempotency_capacity=capacity,
        ),
        clock=fake_clock,
        sleep=fake_clock.sleep,
    )


def assert_failure(
    result: UploadOperationResult,
    state: UploadState,
    boundary: UploadBoundary,
    code: UploadFailureCode,
) -> None:
    assert result.state is state
    assert result.failure is not None
    assert result.failure.boundary is boundary
    assert result.failure.code is code
    assert result.verified is None


@pytest.mark.asyncio
async def test_success_is_single_dispatch_and_duplicate_reuses_exact_evidence() -> None:
    candidate, qualification = candidate_and_qualification()
    transport = FakeTransport()
    uploader = service(transport)

    first = await uploader.execute(candidate, qualification)
    second = await uploader.execute(candidate, qualification)

    assert first == second
    assert first.state is UploadState.VERIFIED
    assert first.verified is not None
    assert first.verified.remote_file.sha256 == qualification.selected_plate.gcode_sha256
    assert transport.uploads == [
        (
            f"klove/{qualification.operation_id}.gcode",
            GCODE,
            qualification.selected_plate.gcode_sha256,
            len(GCODE),
        )
    ]
    assert transport.metadata_calls == 2


@pytest.mark.asyncio
async def test_caller_cancellation_is_shielded_and_duplicate_completes_original() -> None:
    candidate, qualification = candidate_and_qualification()
    transport = FakeTransport()
    transport.release_upload.clear()
    uploader = service(transport)

    caller = asyncio.create_task(uploader.execute(candidate, qualification))
    await transport.upload_entered.wait()
    caller.cancel()
    with pytest.raises(asyncio.CancelledError):
        await caller
    duplicate = asyncio.create_task(uploader.execute(candidate, qualification))
    transport.release_upload.set()

    assert (await duplicate).state is UploadState.VERIFIED
    assert len(transport.uploads) == 1


@pytest.mark.asyncio
async def test_distinct_operations_are_serialized_for_the_printer() -> None:
    candidate, qualification = candidate_and_qualification()
    transport = FakeTransport()
    transport.release_upload.clear()
    uploader = service(transport)
    second_qualification = qualification.model_copy(
        update={
            "operation_id": "66666666-6666-4666-8666-666666666666",
            "idempotency_key": "77777777-7777-4777-8777-777777777777",
        }
    )

    first = asyncio.create_task(uploader.execute(candidate, qualification))
    await transport.upload_entered.wait()
    second = asyncio.create_task(uploader.execute(candidate, second_qualification))
    await asyncio.sleep(0)
    assert len(transport.uploads) == 0
    transport.release_upload.set()

    assert (await first).state is UploadState.VERIFIED
    assert (await second).state is UploadState.VERIFIED
    assert [item[0] for item in transport.uploads] == [
        f"klove/{qualification.operation_id}.gcode",
        f"klove/{second_qualification.operation_id}.gcode",
    ]


@pytest.mark.asyncio
@pytest.mark.parametrize("collision", ["key", "operation"])
async def test_idempotency_or_operation_collision_is_denied(collision: str) -> None:
    candidate, qualification = candidate_and_qualification()
    transport = FakeTransport()
    uploader = service(transport)
    assert (await uploader.execute(candidate, qualification)).state is UploadState.VERIFIED
    updates = (
        {"operation_id": "66666666-6666-4666-8666-666666666666"}
        if collision == "key"
        else {"idempotency_key": "77777777-7777-4777-8777-777777777777"}
    )

    result = await uploader.execute(candidate, qualification.model_copy(update=updates))

    assert_failure(
        result,
        UploadState.DENIED,
        UploadBoundary.IDEMPOTENCY,
        UploadFailureCode.IDEMPOTENCY_CONFLICT,
    )
    assert len(transport.uploads) == 1


@pytest.mark.asyncio
async def test_bounded_journal_fails_closed_at_capacity() -> None:
    candidate, qualification = candidate_and_qualification()
    transport = FakeTransport()
    uploader = service(transport, capacity=1)
    await uploader.execute(candidate, qualification)
    distinct = qualification.model_copy(
        update={
            "operation_id": "66666666-6666-4666-8666-666666666666",
            "idempotency_key": "77777777-7777-4777-8777-777777777777",
        }
    )

    result = await uploader.execute(candidate, distinct)

    assert_failure(
        result,
        UploadState.DENIED,
        UploadBoundary.IDEMPOTENCY,
        UploadFailureCode.CAPACITY_EXHAUSTED,
    )


@pytest.mark.asyncio
@pytest.mark.parametrize("stale", ["printer", "missing_profile", "fingerprint"])
async def test_stale_target_never_reaches_moonraker(stale: str) -> None:
    candidate, qualification = candidate_and_qualification()
    configured = printer()
    if stale == "printer":
        qualification = qualification.model_copy(
            update={
                "target": qualification.target.model_copy(
                    update={"printer_uuid": "88888888-8888-4888-8888-888888888888"}
                )
            }
        )
    elif stale == "missing_profile":
        configured = printer(profiles=())
    else:
        qualification = qualification.model_copy(
            update={
                "target": qualification.target.model_copy(update={"safety_profile_generation": 8})
            }
        )
    transport = FakeTransport()

    result = await service(transport, configured_printer=configured).execute(
        candidate, qualification
    )

    assert_failure(
        result,
        UploadState.DENIED,
        UploadBoundary.QUALIFICATION,
        UploadFailureCode.TARGET_STALE,
    )
    assert transport.uploads == []


@pytest.mark.asyncio
async def test_mismatched_or_changed_source_never_reaches_moonraker() -> None:
    candidate, qualification = candidate_and_qualification()
    transport = FakeTransport()
    mismatched = qualification.model_copy(
        update={
            "selected_plate": qualification.selected_plate.model_copy(
                update={"gcode_sha256": "sha256:" + "0" * 64}
            )
        }
    )
    result = await service(transport).execute(candidate, mismatched)
    assert_failure(
        result,
        UploadState.DENIED,
        UploadBoundary.SOURCE,
        UploadFailureCode.SOURCE_INVALID,
    )

    changed = replace(candidate, source_archive=candidate.source_archive + b"changed")
    result = await service(transport).execute(changed, qualification)
    assert_failure(
        result,
        UploadState.DENIED,
        UploadBoundary.SOURCE,
        UploadFailureCode.SOURCE_INVALID,
    )
    assert transport.uploads == []


@pytest.mark.asyncio
async def test_preflight_and_selected_member_errors_are_bounded_denials(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    candidate, qualification = candidate_and_qualification()
    transport = FakeTransport()

    def broken_inspection(*_args: object, **_kwargs: object) -> object:
        raise ValueError("hostile detail")

    monkeypatch.setattr(upload_module, "inspect_gcode_3mf", broken_inspection)
    result = await service(transport).execute(candidate, qualification)
    assert_failure(
        result,
        UploadState.DENIED,
        UploadBoundary.SOURCE,
        UploadFailureCode.SOURCE_INVALID,
    )

    monkeypatch.undo()

    class BrokenContext:
        def __enter__(self) -> BinaryIO:
            raise ValueError("hostile detail")

        def __exit__(self, *_args: object) -> None:
            return None

    def broken_open(_candidate: ValidatedGcodeCandidate) -> BrokenContext:
        return BrokenContext()

    monkeypatch.setattr(upload_module, "open_selected_gcode", broken_open)
    result = await service(transport).execute(candidate, qualification)
    assert_failure(
        result,
        UploadState.DENIED,
        UploadBoundary.SOURCE,
        UploadFailureCode.SOURCE_INVALID,
    )
    assert "hostile" not in result.model_dump_json()


@pytest.mark.asyncio
@pytest.mark.parametrize("mismatch", ["path", "size"])
async def test_upload_receipt_mismatch_is_outcome_unknown(mismatch: str) -> None:
    candidate, qualification = candidate_and_qualification()
    transport = FakeTransport()
    if mismatch == "path":
        transport.receipt_path = "klove/88888888-8888-4888-8888-888888888888.gcode"
    else:
        transport.receipt_size = len(GCODE) + 1

    result = await service(transport).execute(candidate, qualification)

    assert_failure(
        result,
        UploadState.OUTCOME_UNKNOWN,
        UploadBoundary.REMOTE_FILE,
        UploadFailureCode.REMOTE_MISMATCH,
    )


@pytest.mark.asyncio
async def test_metadata_wait_is_immediate_bounded_and_never_redispatches() -> None:
    candidate, qualification = candidate_and_qualification()
    transport = FakeTransport()
    transport.metadata_values = [None, None, None]
    fake_clock = FakeClock()
    uploader = service(transport, clock=fake_clock)

    first = await uploader.execute(candidate, qualification)
    second = await uploader.execute(candidate, qualification)

    assert first == second
    assert_failure(
        first,
        UploadState.OUTCOME_UNKNOWN,
        UploadBoundary.METADATA,
        UploadFailureCode.METADATA_TIMEOUT,
    )
    assert fake_clock.now == pytest.approx(0.2)
    assert transport.metadata_calls == 3
    assert len(transport.uploads) == 1


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "updates",
    [
        {"path": "klove/88888888-8888-4888-8888-888888888888.gcode"},
        {"size_bytes": len(GCODE) + 1, "gcode_end_byte": len(GCODE) + 1},
        {"modified": Decimal("1700000000.5")},
        {"file_processors": ("preprocess_cancellation",)},
        {"nozzle_diameter_micrometres": 600},
    ],
)
async def test_metadata_mismatch_is_outcome_unknown(updates: dict[str, object]) -> None:
    candidate, qualification = candidate_and_qualification()
    transport = FakeTransport()
    path = f"klove/{qualification.operation_id}.gcode"
    transport.last_size = len(GCODE)
    transport.metadata_values = [transport.metadata_for(path, **updates)]

    result = await service(transport).execute(candidate, qualification)

    assert_failure(
        result,
        UploadState.OUTCOME_UNKNOWN,
        UploadBoundary.METADATA,
        UploadFailureCode.REMOTE_MISMATCH,
    )


@pytest.mark.asyncio
@pytest.mark.parametrize("mismatch", ["size", "digest"])
async def test_remote_file_mismatch_is_outcome_unknown(mismatch: str) -> None:
    candidate, qualification = candidate_and_qualification()
    transport = FakeTransport()
    if mismatch == "size":
        transport.remote_size = len(GCODE) + 1
    else:
        transport.remote_digest = "sha256:" + "0" * 64

    result = await service(transport).execute(candidate, qualification)

    assert_failure(
        result,
        UploadState.OUTCOME_UNKNOWN,
        UploadBoundary.REMOTE_FILE,
        UploadFailureCode.REMOTE_MISMATCH,
    )


@pytest.mark.asyncio
@pytest.mark.parametrize("changed", ["missing", "identity"])
async def test_metadata_change_around_download_is_outcome_unknown(changed: str) -> None:
    candidate, qualification = candidate_and_qualification()
    transport = FakeTransport()
    path = f"klove/{qualification.operation_id}.gcode"
    transport.last_size = len(GCODE)
    first = transport.metadata_for(path)
    second = (
        None
        if changed == "missing"
        else first.model_copy(update={"metadata_uuid": "88888888-8888-4888-8888-888888888888"})
    )
    transport.metadata_values = [first, second]

    result = await service(transport).execute(candidate, qualification)

    assert_failure(
        result,
        UploadState.OUTCOME_UNKNOWN,
        UploadBoundary.METADATA,
        UploadFailureCode.REMOTE_MISMATCH,
    )


@pytest.mark.asyncio
@pytest.mark.parametrize("failure", ["upload", "metadata", "download", "metadata_after"])
async def test_every_transport_ambiguity_is_unknown_and_never_retried(failure: str) -> None:
    candidate, qualification = candidate_and_qualification()
    transport = FakeTransport()
    path = f"klove/{qualification.operation_id}.gcode"
    transport.last_size = len(GCODE)
    if failure == "upload":
        transport.upload_error = True
    elif failure == "metadata":
        transport.metadata_values = [UploadTransportError()]
    elif failure == "download":
        transport.download_error = True
    else:
        transport.metadata_values = [
            transport.metadata_for(path),
            UploadTransportError(),
        ]
    uploader = service(transport)

    first = await uploader.execute(candidate, qualification)
    second = await uploader.execute(candidate, qualification)

    assert first == second
    assert_failure(
        first,
        UploadState.OUTCOME_UNKNOWN,
        UploadBoundary.TRANSPORT,
        UploadFailureCode.TRANSPORT_AMBIGUOUS,
    )
    assert len(transport.uploads) == 1


@pytest.mark.asyncio
async def test_internal_cancellation_after_dispatch_is_terminal_unknown() -> None:
    candidate, qualification = candidate_and_qualification()
    transport = FakeTransport()
    transport.release_upload.clear()
    uploader = service(transport)
    caller = asyncio.create_task(uploader.execute(candidate, qualification))
    await transport.upload_entered.wait()

    entry = uploader._by_key[qualification.idempotency_key]
    entry.task.cancel()

    result = await caller
    assert_failure(
        result,
        UploadState.OUTCOME_UNKNOWN,
        UploadBoundary.TRANSPORT,
        UploadFailureCode.TRANSPORT_AMBIGUOUS,
    )
