from __future__ import annotations

import hashlib
import stat
import struct
from dataclasses import replace
from io import BytesIO
from pathlib import Path
from typing import cast
from zipfile import ZIP_DEFLATED, ZIP_STORED, ZipFile, ZipInfo

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

import klove.domain.artifact_validation as validation
from klove.domain.artifact_validation import (
    ValidatedGcodeCandidate,
    inspect_gcode_3mf,
    open_selected_gcode,
)
from klove.domain.artifacts import (
    ArtifactBoundary,
    ArtifactFailure,
    ArtifactFailureCode,
    ArtifactIntent,
    ArtifactLimits,
)

FIXTURES = Path(__file__).parents[1] / "fixtures" / "artifacts"
SELECTED_PATH = "Metadata/plate_1.gcode"
VALID_GCODE = b"; generated by OrcaSlicer 2.3.0\nG28\nG1 X1.0 Y2.0\n"
CORE_ENTRIES = (
    ("[Content_Types].xml", b"<Types/>"),
    ("_rels/.rels", b"<Relationships/>"),
    ("3D/3dmodel.model", b"<model/>"),
)


def base_intent() -> ArtifactIntent:
    return ArtifactIntent.model_validate_json(
        (FIXTURES / "accepted-intent.json").read_text(encoding="utf-8")
    )


def zip_bytes(
    entries: list[tuple[str | ZipInfo, bytes]] | None = None,
    *,
    compression: int = ZIP_DEFLATED,
    archive_comment: bytes = b"",
) -> bytes:
    members: list[tuple[str | ZipInfo, bytes]] = list(CORE_ENTRIES)
    members.append((SELECTED_PATH, VALID_GCODE))
    if entries is not None:
        members = entries
    target = BytesIO()
    with ZipFile(target, mode="w", compression=compression, allowZip64=True) as bundle:
        for name, content in members:
            bundle.writestr(name, content)
        bundle.comment = archive_comment
    return target.getvalue()


def intent_for(payload: bytes, *, archive_path: str = SELECTED_PATH) -> ArtifactIntent:
    request = base_intent()
    return request.model_copy(
        update={
            "artifact": request.artifact.model_copy(
                update={
                    "archive_sha256": "sha256:" + hashlib.sha256(payload).hexdigest(),
                    "compressed_size_bytes": len(payload),
                }
            ),
            "selected_plate": request.selected_plate.model_copy(
                update={"archive_path": archive_path}
            ),
        }
    )


def inspect(payload: bytes, *, limits: ArtifactLimits | None = None) -> object:
    return inspect_gcode_3mf(
        intent_for(payload),
        payload,
        limits=limits or ArtifactLimits(),
    )


def assert_failure(
    result: object,
    boundary: ArtifactBoundary,
    code: ArtifactFailureCode,
) -> None:
    assert result == ArtifactFailure(boundary=boundary, code=code)


def as_zip64(payload: bytes) -> bytes:
    eocd_offset = len(payload) - 22
    eocd = bytearray(payload[eocd_offset:])
    entries = struct.unpack_from("<H", eocd, 10)[0]
    directory_size = struct.unpack_from("<L", eocd, 12)[0]
    directory_offset = struct.unpack_from("<L", eocd, 16)[0]
    record = struct.pack(
        "<4sQ2H2L4Q",
        b"PK\x06\x06",
        44,
        45,
        45,
        0,
        0,
        entries,
        entries,
        directory_size,
        directory_offset,
    )
    locator = struct.pack("<4sLQL", b"PK\x06\x07", 0, eocd_offset, 1)
    struct.pack_into("<4H2L", eocd, 4, 0, 0, 0xFFFF, 0xFFFF, 0xFFFFFFFF, 0xFFFFFFFF)
    return payload[:eocd_offset] + record + locator + bytes(eocd)


def test_valid_archive_returns_byte_exact_candidate_and_observed_evidence() -> None:
    entries: list[tuple[str | ZipInfo, bytes]] = [
        ("Metadata/", b""),
        ("3D/", b""),
        *CORE_ENTRIES,
        ("Metadata/readme.txt", b"metadata"),
        (SELECTED_PATH, VALID_GCODE),
    ]
    for index, (name, content) in enumerate(entries):
        if isinstance(name, str) and name.endswith("/"):
            info = ZipInfo(name)
            info.create_system = 3
            info.external_attr = (stat.S_IFDIR | 0o755) << 16 | 0x10
            info.compress_type = ZIP_STORED
            entries[index] = (info, content)
    payload = zip_bytes(entries)
    result = inspect_gcode_3mf(intent_for(payload), payload, limits=ArtifactLimits())

    assert isinstance(result, ValidatedGcodeCandidate)
    assert result.source_archive is payload
    assert result.inspection.artifact == intent_for(payload).artifact
    assert not hasattr(result.inspection, "target")
    assert result.inspection.selected_plate.archive_path == SELECTED_PATH
    assert result.inspection.selected_plate.gcode_sha256 == (
        "sha256:" + hashlib.sha256(VALID_GCODE).hexdigest()
    )
    with ZipFile(BytesIO(payload)) as bundle:
        infos = bundle.infolist()
    assert result.inspection.zip_entry_count == len(infos)
    assert result.inspection.archive_expanded_bytes == sum(info.file_size for info in infos)
    assert "source_archive" not in repr(result)


def test_selected_gcode_can_only_reopen_the_exact_inspected_member() -> None:
    payload = zip_bytes()
    candidate = inspect(payload)
    assert isinstance(candidate, ValidatedGcodeCandidate)

    with open_selected_gcode(candidate) as selected:
        assert selected.read() == VALID_GCODE

    missing = replace(
        candidate,
        inspection=candidate.inspection.model_copy(
            update={
                "selected_plate": candidate.inspection.selected_plate.model_copy(
                    update={"archive_path": "Metadata/missing.gcode"}
                )
            }
        ),
    )
    wrong_size = replace(
        candidate,
        inspection=candidate.inspection.model_copy(
            update={
                "selected_plate": candidate.inspection.selected_plate.model_copy(
                    update={"gcode_size_bytes": len(VALID_GCODE) + 1}
                )
            }
        ),
    )
    malformed = replace(candidate, source_archive=b"not-a-zip")
    for value in (missing, wrong_size, malformed):
        with (
            pytest.raises(ValueError, match="selected member is unavailable"),
            open_selected_gcode(value),
        ):
            raise AssertionError("unreachable")


def test_valid_strict_zip64_archive_is_supported() -> None:
    payload = as_zip64(zip_bytes())

    assert isinstance(inspect(payload), ValidatedGcodeCandidate)


@pytest.mark.parametrize(
    ("archive", "limits", "code"),
    [
        (b"not-a-zip", ArtifactLimits(), ArtifactFailureCode.MALFORMED),
        (zip_bytes(archive_comment=b"comment"), ArtifactLimits(), ArtifactFailureCode.MALFORMED),
        (
            zip_bytes(),
            ArtifactLimits(max_archive_compressed_bytes=22),
            ArtifactFailureCode.LIMIT_EXCEEDED,
        ),
    ],
)
def test_truncated_commented_and_oversized_archives_are_denied(
    archive: bytes, limits: ArtifactLimits, code: ArtifactFailureCode
) -> None:
    assert_failure(
        inspect(archive, limits=limits),
        ArtifactBoundary.ARCHIVE
        if code is ArtifactFailureCode.MALFORMED
        else ArtifactBoundary.INTAKE,
        code,
    )


def test_intake_requires_exact_size_digest_and_immutable_bytes_snapshot() -> None:
    payload = zip_bytes()
    request = intent_for(payload)
    wrong_size = request.model_copy(
        update={
            "artifact": request.artifact.model_copy(
                update={"compressed_size_bytes": len(payload) + 1}
            )
        }
    )
    assert_failure(
        inspect_gcode_3mf(wrong_size, payload, limits=ArtifactLimits()),
        ArtifactBoundary.INTAKE,
        ArtifactFailureCode.INTEGRITY_FAILED,
    )
    wrong_digest = request.model_copy(
        update={
            "artifact": request.artifact.model_copy(update={"archive_sha256": "sha256:" + "0" * 64})
        }
    )
    assert_failure(
        inspect_gcode_3mf(wrong_digest, payload, limits=ArtifactLimits()),
        ArtifactBoundary.INTAKE,
        ArtifactFailureCode.INTEGRITY_FAILED,
    )

    assert_failure(
        inspect_gcode_3mf(
            request,
            cast(bytes, bytearray(payload)),
            limits=ArtifactLimits(),
        ),
        ArtifactBoundary.INTAKE,
        ArtifactFailureCode.UNSUPPORTED_ARCHIVE,
    )


def test_parser_fallback_maps_unexpected_zipfile_failure_to_malformed(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    payload = zip_bytes()

    def broken_zipfile(*_args: object, **_kwargs: object) -> ZipFile:
        raise OSError("hostile secret")

    monkeypatch.setattr(validation, "ZipFile", broken_zipfile)
    result = inspect(payload)

    assert_failure(result, ArtifactBoundary.ARCHIVE, ArtifactFailureCode.MALFORMED)
    assert "hostile secret" not in cast(ArtifactFailure, result).model_dump_json()


@settings(max_examples=40, deadline=None)
@given(st.binary(max_size=2048))
def test_arbitrary_zip_like_bytes_always_produce_a_bounded_result(payload: bytes) -> None:
    request = intent_for(payload or b"x")
    result = inspect_gcode_3mf(request, payload or b"x", limits=ArtifactLimits())

    assert isinstance(result, ArtifactFailure | ValidatedGcodeCandidate)
    if isinstance(result, ArtifactFailure):
        assert result.model_dump_json() in {
            ArtifactFailure(boundary=boundary, code=code).model_dump_json()
            for boundary in ArtifactBoundary
            for code in ArtifactFailureCode
        }
